# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from .raw_client import AsyncRawCallsClient, RawCallsClient

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class CallsClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawCallsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawCallsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawCallsClient
        """
        return self._raw_client

    def list(
        self,
        *,
        agent_id: typing.Optional[str] = None,
        status: typing.Optional[str] = None,
        limit: typing.Optional[int] = None,
        offset: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> typing.Any:
        """
        List voice calls made by your AI agents.

        Returns call history with optional filters by agent or status.
        Each entry includes direction (inbound/outbound), duration,
        phone numbers, and current status.

        Filters:
          - agent_id: only calls for a specific AI agent
          - status: "initiated", "in-progress", "completed", or "failed"

        Parameters
        ----------
        agent_id : typing.Optional[str]
            Filter calls by AI agent ID

        status : typing.Optional[str]
            Filter by call status: 'initiated', 'in-progress', 'completed', or 'failed'

        limit : typing.Optional[int]
            Maximum number of calls to return (1-200)

        offset : typing.Optional[int]
            Number of calls to skip for pagination

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Any
            Successful Response

        Examples
        --------
        from agentline_ai import AgentLine

        client = AgentLine(
            token="YOUR_TOKEN",
        )
        client.calls.list()
        """
        _response = self._raw_client.list(
            agent_id=agent_id, status=status, limit=limit, offset=offset, request_options=request_options
        )
        return _response.data

    def create(
        self,
        *,
        agent_id: str,
        to_number: str,
        system_prompt: typing.Optional[str] = OMIT,
        initial_greeting: typing.Optional[str] = OMIT,
        voice_id: typing.Optional[str] = OMIT,
        from_number_id: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> typing.Any:
        """
        Make an outbound phone call from your AI agent.

        Initiates a real phone call from the AI agent's phone number to the
        specified destination. The agent uses its configured system prompt,
        voice, and greeting to conduct the conversation autonomously.

        The AI agent handles the entire call — speech-to-text, LLM reasoning,
        and text-to-speech — in real time. The call transcript is saved
        automatically and can be retrieved via GET /v1/calls/{call_id}/transcript.

        Request body:
          - agent_id: the AI agent making the call
          - to_number: destination phone number in E.164 format (e.g. "+12125551234")
          - from_number_id: (optional) specific number to call from
          - system_prompt: (optional) override the agent's default prompt for this call
          - initial_greeting: (optional) override the agent's greeting for this call
          - voice_id: (optional) override the voice for this call

        Parameters
        ----------
        agent_id : str
            ID of the AI agent making the call (e.g. 'agt_abc123')

        to_number : str
            Destination phone number in E.164 format (e.g. '+12125551234')

        system_prompt : typing.Optional[str]
            Per-call system prompt override. Replaces the agent's default prompt for this call ONLY. If omitted, the agent's default system_prompt is used.

        initial_greeting : typing.Optional[str]
            Per-call greeting override. Replaces the agent's default greeting for this call ONLY. If omitted, the agent's default initial_greeting is used.

        voice_id : typing.Optional[str]
            Override the TTS voice for this call: preset name (e.g. 'female-1') or Cartesia UUID

        from_number_id : typing.Optional[str]
            Specific phone number ID to call from; defaults to the agent's assigned number

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Any
            Successful Response

        Examples
        --------
        from agentline_ai import AgentLine

        client = AgentLine(
            token="YOUR_TOKEN",
        )
        client.calls.create(
            agent_id="agent_id",
            to_number="to_number",
        )
        """
        _response = self._raw_client.create(
            agent_id=agent_id,
            to_number=to_number,
            system_prompt=system_prompt,
            initial_greeting=initial_greeting,
            voice_id=voice_id,
            from_number_id=from_number_id,
            request_options=request_options,
        )
        return _response.data

    def get(self, call_id: str, *, request_options: typing.Optional[RequestOptions] = None) -> typing.Any:
        """
        Get full details of a specific voice call.

        Returns the call's metadata including direction, phone numbers,
        status, duration, AI agent configuration used, and the full
        conversation transcript between the AI agent and the caller.

        Parameters
        ----------
        call_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Any
            Successful Response

        Examples
        --------
        from agentline_ai import AgentLine

        client = AgentLine(
            token="YOUR_TOKEN",
        )
        client.calls.get(
            call_id="call_id",
        )
        """
        _response = self._raw_client.get(call_id, request_options=request_options)
        return _response.data

    def push_context(
        self,
        call_id: str,
        *,
        request: typing.Dict[str, typing.Any],
        token: typing.Optional[str] = None,
        push_token: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> typing.Any:
        """
        Push context into a LIVE relay-mode call (mid-call context injection).

        This is the required way for backend agents (Hermes, OpenClaw, etc.) to
        answer a live caller after a ``call.utterance`` event. Do your work, then
        POST facts here — do NOT only send the answer to WhatsApp/SMS/chat.

        AUTHENTICATION (one of):
          1. **Push token** (preferred — no API key): the ``push_token`` from the
             ``call.utterance`` payload, via ``X-Push-Token`` header, ``?token=``
             query param, or ``push_token`` body field.
          2. **Bearer API key**: ``Authorization: Bearer sk_live_...`` for the
             account that owns the call.

        Body — any of these keys works (``context`` is canonical):
            {"context": "the facts/answer the voice agent should speak"}

        Other accepted keys: ``summary``, ``answer``, ``response``, ``message``,
        ``reply``, ``text``, ``result``.

        Returns:
            delivered=true, status="live"     — voice agent will speak it now
            delivered=true, status="buffered" — caller moved on; held for their
              next question (late pushes are NOT rejected)
            HTTP 410                           — **call has ended.** STOP working
              on this request and abandon any in-flight lookup. No further context
              will be spoken.

        Parameters
        ----------
        call_id : str

        request : typing.Dict[str, typing.Any]

        token : typing.Optional[str]
            Push token (alt to X-Push-Token header / body).

        push_token : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Any
            Successful Response

        Examples
        --------
        from agentline_ai import AgentLine

        client = AgentLine(
            token="YOUR_TOKEN",
        )
        client.calls.push_context(
            call_id="call_id",
            request={"key": "value"},
        )
        """
        _response = self._raw_client.push_context(
            call_id, request=request, token=token, push_token=push_token, request_options=request_options
        )
        return _response.data

    def hangup(self, call_id: str, *, request_options: typing.Optional[RequestOptions] = None) -> typing.Any:
        """
        Hang up an active phone call.

        Programmatically terminates an in-progress voice call. Use this
        when the AI agent needs to end the conversation, or to force-stop
        a call that is no longer needed. The call's final transcript and
        billing are processed automatically after hangup.

        Parameters
        ----------
        call_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Any
            Successful Response

        Examples
        --------
        from agentline_ai import AgentLine

        client = AgentLine(
            token="YOUR_TOKEN",
        )
        client.calls.hangup(
            call_id="call_id",
        )
        """
        _response = self._raw_client.hangup(call_id, request_options=request_options)
        return _response.data

    def get_transcript(self, call_id: str, *, request_options: typing.Optional[RequestOptions] = None) -> typing.Any:
        """
        Get the full conversation transcript for a call.

        Returns the complete speech-to-text transcript of the phone call,
        with each turn labeled by role ("human" for the caller, "assistant"
        for the AI agent). Useful for reviewing what was said on the call,
        extracting information, or auditing AI agent behavior.

        Parameters
        ----------
        call_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Any
            Successful Response

        Examples
        --------
        from agentline_ai import AgentLine

        client = AgentLine(
            token="YOUR_TOKEN",
        )
        client.calls.get_transcript(
            call_id="call_id",
        )
        """
        _response = self._raw_client.get_transcript(call_id, request_options=request_options)
        return _response.data


class AsyncCallsClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawCallsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawCallsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawCallsClient
        """
        return self._raw_client

    async def list(
        self,
        *,
        agent_id: typing.Optional[str] = None,
        status: typing.Optional[str] = None,
        limit: typing.Optional[int] = None,
        offset: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> typing.Any:
        """
        List voice calls made by your AI agents.

        Returns call history with optional filters by agent or status.
        Each entry includes direction (inbound/outbound), duration,
        phone numbers, and current status.

        Filters:
          - agent_id: only calls for a specific AI agent
          - status: "initiated", "in-progress", "completed", or "failed"

        Parameters
        ----------
        agent_id : typing.Optional[str]
            Filter calls by AI agent ID

        status : typing.Optional[str]
            Filter by call status: 'initiated', 'in-progress', 'completed', or 'failed'

        limit : typing.Optional[int]
            Maximum number of calls to return (1-200)

        offset : typing.Optional[int]
            Number of calls to skip for pagination

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Any
            Successful Response

        Examples
        --------
        import asyncio

        from agentline_ai import AsyncAgentLine

        client = AsyncAgentLine(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.calls.list()


        asyncio.run(main())
        """
        _response = await self._raw_client.list(
            agent_id=agent_id, status=status, limit=limit, offset=offset, request_options=request_options
        )
        return _response.data

    async def create(
        self,
        *,
        agent_id: str,
        to_number: str,
        system_prompt: typing.Optional[str] = OMIT,
        initial_greeting: typing.Optional[str] = OMIT,
        voice_id: typing.Optional[str] = OMIT,
        from_number_id: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> typing.Any:
        """
        Make an outbound phone call from your AI agent.

        Initiates a real phone call from the AI agent's phone number to the
        specified destination. The agent uses its configured system prompt,
        voice, and greeting to conduct the conversation autonomously.

        The AI agent handles the entire call — speech-to-text, LLM reasoning,
        and text-to-speech — in real time. The call transcript is saved
        automatically and can be retrieved via GET /v1/calls/{call_id}/transcript.

        Request body:
          - agent_id: the AI agent making the call
          - to_number: destination phone number in E.164 format (e.g. "+12125551234")
          - from_number_id: (optional) specific number to call from
          - system_prompt: (optional) override the agent's default prompt for this call
          - initial_greeting: (optional) override the agent's greeting for this call
          - voice_id: (optional) override the voice for this call

        Parameters
        ----------
        agent_id : str
            ID of the AI agent making the call (e.g. 'agt_abc123')

        to_number : str
            Destination phone number in E.164 format (e.g. '+12125551234')

        system_prompt : typing.Optional[str]
            Per-call system prompt override. Replaces the agent's default prompt for this call ONLY. If omitted, the agent's default system_prompt is used.

        initial_greeting : typing.Optional[str]
            Per-call greeting override. Replaces the agent's default greeting for this call ONLY. If omitted, the agent's default initial_greeting is used.

        voice_id : typing.Optional[str]
            Override the TTS voice for this call: preset name (e.g. 'female-1') or Cartesia UUID

        from_number_id : typing.Optional[str]
            Specific phone number ID to call from; defaults to the agent's assigned number

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Any
            Successful Response

        Examples
        --------
        import asyncio

        from agentline_ai import AsyncAgentLine

        client = AsyncAgentLine(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.calls.create(
                agent_id="agent_id",
                to_number="to_number",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.create(
            agent_id=agent_id,
            to_number=to_number,
            system_prompt=system_prompt,
            initial_greeting=initial_greeting,
            voice_id=voice_id,
            from_number_id=from_number_id,
            request_options=request_options,
        )
        return _response.data

    async def get(self, call_id: str, *, request_options: typing.Optional[RequestOptions] = None) -> typing.Any:
        """
        Get full details of a specific voice call.

        Returns the call's metadata including direction, phone numbers,
        status, duration, AI agent configuration used, and the full
        conversation transcript between the AI agent and the caller.

        Parameters
        ----------
        call_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Any
            Successful Response

        Examples
        --------
        import asyncio

        from agentline_ai import AsyncAgentLine

        client = AsyncAgentLine(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.calls.get(
                call_id="call_id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get(call_id, request_options=request_options)
        return _response.data

    async def push_context(
        self,
        call_id: str,
        *,
        request: typing.Dict[str, typing.Any],
        token: typing.Optional[str] = None,
        push_token: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> typing.Any:
        """
        Push context into a LIVE relay-mode call (mid-call context injection).

        This is the required way for backend agents (Hermes, OpenClaw, etc.) to
        answer a live caller after a ``call.utterance`` event. Do your work, then
        POST facts here — do NOT only send the answer to WhatsApp/SMS/chat.

        AUTHENTICATION (one of):
          1. **Push token** (preferred — no API key): the ``push_token`` from the
             ``call.utterance`` payload, via ``X-Push-Token`` header, ``?token=``
             query param, or ``push_token`` body field.
          2. **Bearer API key**: ``Authorization: Bearer sk_live_...`` for the
             account that owns the call.

        Body — any of these keys works (``context`` is canonical):
            {"context": "the facts/answer the voice agent should speak"}

        Other accepted keys: ``summary``, ``answer``, ``response``, ``message``,
        ``reply``, ``text``, ``result``.

        Returns:
            delivered=true, status="live"     — voice agent will speak it now
            delivered=true, status="buffered" — caller moved on; held for their
              next question (late pushes are NOT rejected)
            HTTP 410                           — **call has ended.** STOP working
              on this request and abandon any in-flight lookup. No further context
              will be spoken.

        Parameters
        ----------
        call_id : str

        request : typing.Dict[str, typing.Any]

        token : typing.Optional[str]
            Push token (alt to X-Push-Token header / body).

        push_token : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Any
            Successful Response

        Examples
        --------
        import asyncio

        from agentline_ai import AsyncAgentLine

        client = AsyncAgentLine(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.calls.push_context(
                call_id="call_id",
                request={"key": "value"},
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.push_context(
            call_id, request=request, token=token, push_token=push_token, request_options=request_options
        )
        return _response.data

    async def hangup(self, call_id: str, *, request_options: typing.Optional[RequestOptions] = None) -> typing.Any:
        """
        Hang up an active phone call.

        Programmatically terminates an in-progress voice call. Use this
        when the AI agent needs to end the conversation, or to force-stop
        a call that is no longer needed. The call's final transcript and
        billing are processed automatically after hangup.

        Parameters
        ----------
        call_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Any
            Successful Response

        Examples
        --------
        import asyncio

        from agentline_ai import AsyncAgentLine

        client = AsyncAgentLine(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.calls.hangup(
                call_id="call_id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.hangup(call_id, request_options=request_options)
        return _response.data

    async def get_transcript(
        self, call_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> typing.Any:
        """
        Get the full conversation transcript for a call.

        Returns the complete speech-to-text transcript of the phone call,
        with each turn labeled by role ("human" for the caller, "assistant"
        for the AI agent). Useful for reviewing what was said on the call,
        extracting information, or auditing AI agent behavior.

        Parameters
        ----------
        call_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Any
            Successful Response

        Examples
        --------
        import asyncio

        from agentline_ai import AsyncAgentLine

        client = AsyncAgentLine(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.calls.get_transcript(
                call_id="call_id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get_transcript(call_id, request_options=request_options)
        return _response.data
