# This file was auto-generated by Fern from our API Definition.

import typing
from json.decoder import JSONDecodeError

from ..core.api_error import ApiError
from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.http_response import AsyncHttpResponse, HttpResponse
from ..core.jsonable_encoder import encode_path_param
from ..core.parse_error import ParsingError
from ..core.pydantic_utilities import parse_obj_as
from ..core.request_options import RequestOptions
from ..errors.unprocessable_entity_error import UnprocessableEntityError
from ..types.http_validation_error import HttpValidationError
from pydantic import ValidationError

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class RawCallsClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._client_wrapper = client_wrapper

    def list(
        self,
        *,
        agent_id: typing.Optional[str] = None,
        status: typing.Optional[str] = None,
        limit: typing.Optional[int] = None,
        offset: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[typing.Any]:
        """
        List voice calls made by your AI agents.

        Returns call history with optional filters by agent or status.
        Each entry includes direction (inbound/outbound), duration,
        phone numbers, and current status.

        Filters:
          - agent_id: only calls for a specific AI agent
          - status: "initiated", "in-progress", "completed", or "failed"

        Parameters
        ----------
        agent_id : typing.Optional[str]
            Filter calls by AI agent ID

        status : typing.Optional[str]
            Filter by call status: 'initiated', 'in-progress', 'completed', or 'failed'

        limit : typing.Optional[int]
            Maximum number of calls to return (1-200)

        offset : typing.Optional[int]
            Number of calls to skip for pagination

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[typing.Any]
            Successful Response
        """
        _response = self._client_wrapper.httpx_client.request(
            "v1/calls",
            method="GET",
            params={
                "agent_id": agent_id,
                "status": status,
                "limit": limit,
                "offset": offset,
            },
            request_options=request_options,
        )
        try:
            if _response is None or not _response.text.strip():
                return HttpResponse(response=_response, data=None)
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    typing.Any,
                    parse_obj_as(
                        type_=typing.Any,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        HttpValidationError,
                        parse_obj_as(
                            type_=HttpValidationError,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def create(
        self,
        *,
        agent_id: str,
        to_number: str,
        system_prompt: typing.Optional[str] = OMIT,
        initial_greeting: typing.Optional[str] = OMIT,
        voice_id: typing.Optional[str] = OMIT,
        from_number_id: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[typing.Any]:
        """
        Make an outbound phone call from your AI agent.

        Initiates a real phone call from the AI agent's phone number to the
        specified destination. The agent uses its configured system prompt,
        voice, and greeting to conduct the conversation autonomously.

        The AI agent handles the entire call — speech-to-text, LLM reasoning,
        and text-to-speech — in real time. The call transcript is saved
        automatically and can be retrieved via GET /v1/calls/{call_id}/transcript.

        Request body:
          - agent_id: the AI agent making the call
          - to_number: destination phone number in E.164 format (e.g. "+12125551234")
          - from_number_id: (optional) specific number to call from
          - system_prompt: (optional) override the agent's default prompt for this call
          - initial_greeting: (optional) override the agent's greeting for this call
          - voice_id: (optional) override the voice for this call

        Parameters
        ----------
        agent_id : str
            ID of the AI agent making the call (e.g. 'agt_abc123')

        to_number : str
            Destination phone number in E.164 format (e.g. '+12125551234')

        system_prompt : typing.Optional[str]
            Per-call system prompt override. Replaces the agent's default prompt for this call ONLY. If omitted, the agent's default system_prompt is used.

        initial_greeting : typing.Optional[str]
            Per-call greeting override. Replaces the agent's default greeting for this call ONLY. If omitted, the agent's default initial_greeting is used.

        voice_id : typing.Optional[str]
            Override the TTS voice for this call: preset name (e.g. 'female-1') or Cartesia UUID

        from_number_id : typing.Optional[str]
            Specific phone number ID to call from; defaults to the agent's assigned number

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[typing.Any]
            Successful Response
        """
        _response = self._client_wrapper.httpx_client.request(
            "v1/calls",
            method="POST",
            json={
                "agent_id": agent_id,
                "to_number": to_number,
                "system_prompt": system_prompt,
                "initial_greeting": initial_greeting,
                "voice_id": voice_id,
                "from_number_id": from_number_id,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if _response is None or not _response.text.strip():
                return HttpResponse(response=_response, data=None)
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    typing.Any,
                    parse_obj_as(
                        type_=typing.Any,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        HttpValidationError,
                        parse_obj_as(
                            type_=HttpValidationError,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def get(self, call_id: str, *, request_options: typing.Optional[RequestOptions] = None) -> HttpResponse[typing.Any]:
        """
        Get full details of a specific voice call.

        Returns the call's metadata including direction, phone numbers,
        status, duration, AI agent configuration used, and the full
        conversation transcript between the AI agent and the caller.

        Parameters
        ----------
        call_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[typing.Any]
            Successful Response
        """
        _response = self._client_wrapper.httpx_client.request(
            f"v1/calls/{encode_path_param(call_id)}",
            method="GET",
            request_options=request_options,
        )
        try:
            if _response is None or not _response.text.strip():
                return HttpResponse(response=_response, data=None)
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    typing.Any,
                    parse_obj_as(
                        type_=typing.Any,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        HttpValidationError,
                        parse_obj_as(
                            type_=HttpValidationError,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def push_context(
        self,
        call_id: str,
        *,
        request: typing.Dict[str, typing.Any],
        token: typing.Optional[str] = None,
        push_token: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[typing.Any]:
        """
        Push context into a LIVE relay-mode call (mid-call context injection).

        This is the required way for backend agents (Hermes, OpenClaw, etc.) to
        answer a live caller after a ``call.utterance`` event. Do your work, then
        POST facts here — do NOT only send the answer to WhatsApp/SMS/chat.

        AUTHENTICATION (one of):
          1. **Push token** (preferred — no API key): the ``push_token`` from the
             ``call.utterance`` payload, via ``X-Push-Token`` header, ``?token=``
             query param, or ``push_token`` body field.
          2. **Bearer API key**: ``Authorization: Bearer sk_live_...`` for the
             account that owns the call.

        Body — any of these keys works (``context`` is canonical):
            {"context": "the facts/answer the voice agent should speak"}

        Other accepted keys: ``summary``, ``answer``, ``response``, ``message``,
        ``reply``, ``text``, ``result``.

        Returns:
            delivered=true, status="live"     — voice agent will speak it now
            delivered=true, status="buffered" — caller moved on; held for their
              next question (late pushes are NOT rejected)
            HTTP 410                           — **call has ended.** STOP working
              on this request and abandon any in-flight lookup. No further context
              will be spoken.

        Parameters
        ----------
        call_id : str

        request : typing.Dict[str, typing.Any]

        token : typing.Optional[str]
            Push token (alt to X-Push-Token header / body).

        push_token : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[typing.Any]
            Successful Response
        """
        _response = self._client_wrapper.httpx_client.request(
            f"v1/calls/{encode_path_param(call_id)}/context",
            method="POST",
            params={
                "token": token,
            },
            json=request,
            headers={
                "content-type": "application/json",
                "X-Push-Token": str(push_token) if push_token is not None else None,
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if _response is None or not _response.text.strip():
                return HttpResponse(response=_response, data=None)
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    typing.Any,
                    parse_obj_as(
                        type_=typing.Any,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        HttpValidationError,
                        parse_obj_as(
                            type_=HttpValidationError,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def hangup(
        self, call_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> HttpResponse[typing.Any]:
        """
        Hang up an active phone call.

        Programmatically terminates an in-progress voice call. Use this
        when the AI agent needs to end the conversation, or to force-stop
        a call that is no longer needed. The call's final transcript and
        billing are processed automatically after hangup.

        Parameters
        ----------
        call_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[typing.Any]
            Successful Response
        """
        _response = self._client_wrapper.httpx_client.request(
            f"v1/calls/{encode_path_param(call_id)}/hangup",
            method="POST",
            request_options=request_options,
        )
        try:
            if _response is None or not _response.text.strip():
                return HttpResponse(response=_response, data=None)
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    typing.Any,
                    parse_obj_as(
                        type_=typing.Any,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        HttpValidationError,
                        parse_obj_as(
                            type_=HttpValidationError,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def get_transcript(
        self, call_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> HttpResponse[typing.Any]:
        """
        Get the full conversation transcript for a call.

        Returns the complete speech-to-text transcript of the phone call,
        with each turn labeled by role ("human" for the caller, "assistant"
        for the AI agent). Useful for reviewing what was said on the call,
        extracting information, or auditing AI agent behavior.

        Parameters
        ----------
        call_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[typing.Any]
            Successful Response
        """
        _response = self._client_wrapper.httpx_client.request(
            f"v1/calls/{encode_path_param(call_id)}/transcript",
            method="GET",
            request_options=request_options,
        )
        try:
            if _response is None or not _response.text.strip():
                return HttpResponse(response=_response, data=None)
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    typing.Any,
                    parse_obj_as(
                        type_=typing.Any,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        HttpValidationError,
                        parse_obj_as(
                            type_=HttpValidationError,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)


class AsyncRawCallsClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._client_wrapper = client_wrapper

    async def list(
        self,
        *,
        agent_id: typing.Optional[str] = None,
        status: typing.Optional[str] = None,
        limit: typing.Optional[int] = None,
        offset: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[typing.Any]:
        """
        List voice calls made by your AI agents.

        Returns call history with optional filters by agent or status.
        Each entry includes direction (inbound/outbound), duration,
        phone numbers, and current status.

        Filters:
          - agent_id: only calls for a specific AI agent
          - status: "initiated", "in-progress", "completed", or "failed"

        Parameters
        ----------
        agent_id : typing.Optional[str]
            Filter calls by AI agent ID

        status : typing.Optional[str]
            Filter by call status: 'initiated', 'in-progress', 'completed', or 'failed'

        limit : typing.Optional[int]
            Maximum number of calls to return (1-200)

        offset : typing.Optional[int]
            Number of calls to skip for pagination

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[typing.Any]
            Successful Response
        """
        _response = await self._client_wrapper.httpx_client.request(
            "v1/calls",
            method="GET",
            params={
                "agent_id": agent_id,
                "status": status,
                "limit": limit,
                "offset": offset,
            },
            request_options=request_options,
        )
        try:
            if _response is None or not _response.text.strip():
                return AsyncHttpResponse(response=_response, data=None)
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    typing.Any,
                    parse_obj_as(
                        type_=typing.Any,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        HttpValidationError,
                        parse_obj_as(
                            type_=HttpValidationError,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def create(
        self,
        *,
        agent_id: str,
        to_number: str,
        system_prompt: typing.Optional[str] = OMIT,
        initial_greeting: typing.Optional[str] = OMIT,
        voice_id: typing.Optional[str] = OMIT,
        from_number_id: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[typing.Any]:
        """
        Make an outbound phone call from your AI agent.

        Initiates a real phone call from the AI agent's phone number to the
        specified destination. The agent uses its configured system prompt,
        voice, and greeting to conduct the conversation autonomously.

        The AI agent handles the entire call — speech-to-text, LLM reasoning,
        and text-to-speech — in real time. The call transcript is saved
        automatically and can be retrieved via GET /v1/calls/{call_id}/transcript.

        Request body:
          - agent_id: the AI agent making the call
          - to_number: destination phone number in E.164 format (e.g. "+12125551234")
          - from_number_id: (optional) specific number to call from
          - system_prompt: (optional) override the agent's default prompt for this call
          - initial_greeting: (optional) override the agent's greeting for this call
          - voice_id: (optional) override the voice for this call

        Parameters
        ----------
        agent_id : str
            ID of the AI agent making the call (e.g. 'agt_abc123')

        to_number : str
            Destination phone number in E.164 format (e.g. '+12125551234')

        system_prompt : typing.Optional[str]
            Per-call system prompt override. Replaces the agent's default prompt for this call ONLY. If omitted, the agent's default system_prompt is used.

        initial_greeting : typing.Optional[str]
            Per-call greeting override. Replaces the agent's default greeting for this call ONLY. If omitted, the agent's default initial_greeting is used.

        voice_id : typing.Optional[str]
            Override the TTS voice for this call: preset name (e.g. 'female-1') or Cartesia UUID

        from_number_id : typing.Optional[str]
            Specific phone number ID to call from; defaults to the agent's assigned number

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[typing.Any]
            Successful Response
        """
        _response = await self._client_wrapper.httpx_client.request(
            "v1/calls",
            method="POST",
            json={
                "agent_id": agent_id,
                "to_number": to_number,
                "system_prompt": system_prompt,
                "initial_greeting": initial_greeting,
                "voice_id": voice_id,
                "from_number_id": from_number_id,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if _response is None or not _response.text.strip():
                return AsyncHttpResponse(response=_response, data=None)
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    typing.Any,
                    parse_obj_as(
                        type_=typing.Any,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        HttpValidationError,
                        parse_obj_as(
                            type_=HttpValidationError,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def get(
        self, call_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> AsyncHttpResponse[typing.Any]:
        """
        Get full details of a specific voice call.

        Returns the call's metadata including direction, phone numbers,
        status, duration, AI agent configuration used, and the full
        conversation transcript between the AI agent and the caller.

        Parameters
        ----------
        call_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[typing.Any]
            Successful Response
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"v1/calls/{encode_path_param(call_id)}",
            method="GET",
            request_options=request_options,
        )
        try:
            if _response is None or not _response.text.strip():
                return AsyncHttpResponse(response=_response, data=None)
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    typing.Any,
                    parse_obj_as(
                        type_=typing.Any,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        HttpValidationError,
                        parse_obj_as(
                            type_=HttpValidationError,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def push_context(
        self,
        call_id: str,
        *,
        request: typing.Dict[str, typing.Any],
        token: typing.Optional[str] = None,
        push_token: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[typing.Any]:
        """
        Push context into a LIVE relay-mode call (mid-call context injection).

        This is the required way for backend agents (Hermes, OpenClaw, etc.) to
        answer a live caller after a ``call.utterance`` event. Do your work, then
        POST facts here — do NOT only send the answer to WhatsApp/SMS/chat.

        AUTHENTICATION (one of):
          1. **Push token** (preferred — no API key): the ``push_token`` from the
             ``call.utterance`` payload, via ``X-Push-Token`` header, ``?token=``
             query param, or ``push_token`` body field.
          2. **Bearer API key**: ``Authorization: Bearer sk_live_...`` for the
             account that owns the call.

        Body — any of these keys works (``context`` is canonical):
            {"context": "the facts/answer the voice agent should speak"}

        Other accepted keys: ``summary``, ``answer``, ``response``, ``message``,
        ``reply``, ``text``, ``result``.

        Returns:
            delivered=true, status="live"     — voice agent will speak it now
            delivered=true, status="buffered" — caller moved on; held for their
              next question (late pushes are NOT rejected)
            HTTP 410                           — **call has ended.** STOP working
              on this request and abandon any in-flight lookup. No further context
              will be spoken.

        Parameters
        ----------
        call_id : str

        request : typing.Dict[str, typing.Any]

        token : typing.Optional[str]
            Push token (alt to X-Push-Token header / body).

        push_token : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[typing.Any]
            Successful Response
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"v1/calls/{encode_path_param(call_id)}/context",
            method="POST",
            params={
                "token": token,
            },
            json=request,
            headers={
                "content-type": "application/json",
                "X-Push-Token": str(push_token) if push_token is not None else None,
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if _response is None or not _response.text.strip():
                return AsyncHttpResponse(response=_response, data=None)
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    typing.Any,
                    parse_obj_as(
                        type_=typing.Any,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        HttpValidationError,
                        parse_obj_as(
                            type_=HttpValidationError,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def hangup(
        self, call_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> AsyncHttpResponse[typing.Any]:
        """
        Hang up an active phone call.

        Programmatically terminates an in-progress voice call. Use this
        when the AI agent needs to end the conversation, or to force-stop
        a call that is no longer needed. The call's final transcript and
        billing are processed automatically after hangup.

        Parameters
        ----------
        call_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[typing.Any]
            Successful Response
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"v1/calls/{encode_path_param(call_id)}/hangup",
            method="POST",
            request_options=request_options,
        )
        try:
            if _response is None or not _response.text.strip():
                return AsyncHttpResponse(response=_response, data=None)
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    typing.Any,
                    parse_obj_as(
                        type_=typing.Any,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        HttpValidationError,
                        parse_obj_as(
                            type_=HttpValidationError,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def get_transcript(
        self, call_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> AsyncHttpResponse[typing.Any]:
        """
        Get the full conversation transcript for a call.

        Returns the complete speech-to-text transcript of the phone call,
        with each turn labeled by role ("human" for the caller, "assistant"
        for the AI agent). Useful for reviewing what was said on the call,
        extracting information, or auditing AI agent behavior.

        Parameters
        ----------
        call_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[typing.Any]
            Successful Response
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"v1/calls/{encode_path_param(call_id)}/transcript",
            method="GET",
            request_options=request_options,
        )
        try:
            if _response is None or not _response.text.strip():
                return AsyncHttpResponse(response=_response, data=None)
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    typing.Any,
                    parse_obj_as(
                        type_=typing.Any,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        HttpValidationError,
                        parse_obj_as(
                            type_=HttpValidationError,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)
