# This file was auto-generated by Fern from our API Definition.

# isort: skip_file

import typing
from importlib import import_module

if typing.TYPE_CHECKING:
    from .agent_out import AgentOut
    from .feedback_category import FeedbackCategory
    from .feedback_create import FeedbackCreate
    from .feedback_out import FeedbackOut
    from .feedback_severity import FeedbackSeverity
    from .http_validation_error import HttpValidationError
    from .otp_request import OtpRequest
    from .topup_request import TopupRequest
    from .validation_error import ValidationError
    from .validation_error_loc_item import ValidationErrorLocItem
    from .verify_request import VerifyRequest
    from .webhook_created import WebhookCreated
_dynamic_imports: typing.Dict[str, str] = {
    "AgentOut": ".agent_out",
    "FeedbackCategory": ".feedback_category",
    "FeedbackCreate": ".feedback_create",
    "FeedbackOut": ".feedback_out",
    "FeedbackSeverity": ".feedback_severity",
    "HttpValidationError": ".http_validation_error",
    "OtpRequest": ".otp_request",
    "TopupRequest": ".topup_request",
    "ValidationError": ".validation_error",
    "ValidationErrorLocItem": ".validation_error_loc_item",
    "VerifyRequest": ".verify_request",
    "WebhookCreated": ".webhook_created",
}


def __getattr__(attr_name: str) -> typing.Any:
    module_name = _dynamic_imports.get(attr_name)
    if module_name is None:
        raise AttributeError(f"No {attr_name} found in _dynamic_imports for module name -> {__name__}")
    try:
        module = import_module(module_name, __package__)
        if module_name == f".{attr_name}":
            return module
        else:
            return getattr(module, attr_name)
    except ImportError as e:
        raise ImportError(f"Failed to import {attr_name} from {module_name}: {e}") from e
    except AttributeError as e:
        raise AttributeError(f"Failed to get {attr_name} from {module_name}: {e}") from e


def __dir__():
    lazy_attrs = list(_dynamic_imports.keys())
    return sorted(lazy_attrs)


__all__ = [
    "AgentOut",
    "FeedbackCategory",
    "FeedbackCreate",
    "FeedbackOut",
    "FeedbackSeverity",
    "HttpValidationError",
    "OtpRequest",
    "TopupRequest",
    "ValidationError",
    "ValidationErrorLocItem",
    "VerifyRequest",
    "WebhookCreated",
]
