# This file was auto-generated by Fern from our API Definition.

# isort: skip_file

import typing
from importlib import import_module

if typing.TYPE_CHECKING:
    from .agent_id_poll_request import AgentIdPollRequest
    from .agent_id_start_request import AgentIdStartRequest
    from .agent_out import AgentOut
    from .feedback_category import FeedbackCategory
    from .feedback_create import FeedbackCreate
    from .feedback_out import FeedbackOut
    from .feedback_severity import FeedbackSeverity
    from .http_validation_error import HttpValidationError
    from .keyless_agent_update import KeylessAgentUpdate
    from .keyless_buy_body import KeylessBuyBody
    from .keyless_call_body import KeylessCallBody
    from .keyless_credit_body import KeylessCreditBody
    from .keyless_events_body import KeylessEventsBody
    from .keyless_list_body import KeylessListBody
    from .keyless_renew_body import KeylessRenewBody
    from .keyless_transcript_body import KeylessTranscriptBody
    from .keyless_webhook_body import KeylessWebhookBody
    from .otp_request import OtpRequest
    from .pay_discovery_body import PayDiscoveryBody
    from .topup_request import TopupRequest
    from .validation_error import ValidationError
    from .validation_error_loc_item import ValidationErrorLocItem
    from .verify_request import VerifyRequest
    from .webhook_created import WebhookCreated
_dynamic_imports: typing.Dict[str, str] = {
    "AgentIdPollRequest": ".agent_id_poll_request",
    "AgentIdStartRequest": ".agent_id_start_request",
    "AgentOut": ".agent_out",
    "FeedbackCategory": ".feedback_category",
    "FeedbackCreate": ".feedback_create",
    "FeedbackOut": ".feedback_out",
    "FeedbackSeverity": ".feedback_severity",
    "HttpValidationError": ".http_validation_error",
    "KeylessAgentUpdate": ".keyless_agent_update",
    "KeylessBuyBody": ".keyless_buy_body",
    "KeylessCallBody": ".keyless_call_body",
    "KeylessCreditBody": ".keyless_credit_body",
    "KeylessEventsBody": ".keyless_events_body",
    "KeylessListBody": ".keyless_list_body",
    "KeylessRenewBody": ".keyless_renew_body",
    "KeylessTranscriptBody": ".keyless_transcript_body",
    "KeylessWebhookBody": ".keyless_webhook_body",
    "OtpRequest": ".otp_request",
    "PayDiscoveryBody": ".pay_discovery_body",
    "TopupRequest": ".topup_request",
    "ValidationError": ".validation_error",
    "ValidationErrorLocItem": ".validation_error_loc_item",
    "VerifyRequest": ".verify_request",
    "WebhookCreated": ".webhook_created",
}


def __getattr__(attr_name: str) -> typing.Any:
    module_name = _dynamic_imports.get(attr_name)
    if module_name is None:
        raise AttributeError(f"No {attr_name} found in _dynamic_imports for module name -> {__name__}")
    try:
        module = import_module(module_name, __package__)
        if module_name == f".{attr_name}":
            return module
        else:
            return getattr(module, attr_name)
    except ImportError as e:
        raise ImportError(f"Failed to import {attr_name} from {module_name}: {e}") from e
    except AttributeError as e:
        raise AttributeError(f"Failed to get {attr_name} from {module_name}: {e}") from e


def __dir__():
    lazy_attrs = list(_dynamic_imports.keys())
    return sorted(lazy_attrs)


__all__ = [
    "AgentIdPollRequest",
    "AgentIdStartRequest",
    "AgentOut",
    "FeedbackCategory",
    "FeedbackCreate",
    "FeedbackOut",
    "FeedbackSeverity",
    "HttpValidationError",
    "KeylessAgentUpdate",
    "KeylessBuyBody",
    "KeylessCallBody",
    "KeylessCreditBody",
    "KeylessEventsBody",
    "KeylessListBody",
    "KeylessRenewBody",
    "KeylessTranscriptBody",
    "KeylessWebhookBody",
    "OtpRequest",
    "PayDiscoveryBody",
    "TopupRequest",
    "ValidationError",
    "ValidationErrorLocItem",
    "VerifyRequest",
    "WebhookCreated",
]
