# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class Action(UniversalBaseModel):
    operation: str = pydantic.Field()
    """
    One of: buy_phone_number, create_agent, delete_agent, delete_webhook, hangup_call, make_outbound_call, release_phone_number, reset_account_voice, set_account_voice, set_webhook, submit_feedback, test_webhook, update_agent
    """

    arguments: typing.Optional[typing.Dict[str, typing.Any]] = pydantic.Field(default=None)
    """
    Named endpoint arguments; request fields go under body. Never include credentials.
    """

    request_id: str = pydantic.Field()
    """
    Stable caller-generated retry key; reuse for the same intended action.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
