# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class AgentOut(UniversalBaseModel):
    id: str = pydantic.Field()
    """
    Unique agent identifier (e.g. 'agt_abc123')
    """

    account_id: str = pydantic.Field()
    """
    Account that owns this agent
    """

    name: str = pydantic.Field()
    """
    Display name of the AI voice agent
    """

    system_prompt: typing.Optional[str] = pydantic.Field(default=None)
    """
    Default system prompt for all calls (can be overridden per-call)
    """

    initial_greeting: typing.Optional[str] = pydantic.Field(default=None)
    """
    Default greeting for all calls (can be overridden per-call)
    """

    voice_id: typing.Optional[str] = pydantic.Field(default=None)
    """
    TTS voice preset or Cartesia UUID
    """

    transfer_number: typing.Optional[str] = pydantic.Field(default=None)
    """
    Phone number for call transfers
    """

    voicemail_message: typing.Optional[str] = pydantic.Field(default=None)
    """
    Message left on voicemail
    """

    owner_phone: typing.Optional[str] = pydantic.Field(default=None)
    """
    Owner's phone number for task mode
    """

    created_at: dt.datetime = pydantic.Field()
    """
    When the agent was created
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
