# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .call_context_disposition import CallContextDisposition


class CallContext(UniversalBaseModel):
    context: typing.Optional[str] = pydantic.Field(default=None)
    """
    Facts for the voice agent to use in its own words. Not read aloud verbatim. Never include credentials.
    """

    turn_id: typing.Optional[str] = pydantic.Field(default=None)
    """
    Open question to answer, from list_call_turns. Omit to add call facts at any time.
    """

    disposition: typing.Optional[CallContextDisposition] = pydantic.Field(default=None)
    """
    facts: call facts (or settles an open turn). partial: one fact so far, turn stays open. progress: not spoken. done/failed/noop: settle the turn.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
