# This file was auto-generated by Fern from our API Definition.

import typing

CallContextDisposition = typing.Union[
    typing.Literal["facts", "partial", "progress", "done", "failed", "noop"], typing.Any
]
