# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .feedback_category import FeedbackCategory
from .feedback_severity import FeedbackSeverity


class FeedbackCreate(UniversalBaseModel):
    category: FeedbackCategory = pydantic.Field()
    """
    Type of feedback: 'bug' (something broken / not working), 'feature_request' (want a new capability), 'difficulty' (hard or confusing to use), or 'feedback' (general comment or praise)
    """

    message: str = pydantic.Field()
    """
    Detailed description of the feedback, issue, or request. For bugs, include what you expected vs. what actually happened.
    """

    subject: typing.Optional[str] = pydantic.Field(default=None)
    """
    Short summary title for the feedback (optional)
    """

    severity: typing.Optional[FeedbackSeverity] = pydantic.Field(default=None)
    """
    Impact level, mainly relevant for bugs: 'low', 'normal', 'high', or 'critical'
    """

    agent_id: typing.Optional[str] = pydantic.Field(default=None)
    """
    ID of the AI agent this feedback relates to, if applicable
    """

    contact_email: typing.Optional[str] = pydantic.Field(default=None)
    """
    Email address for follow-up about this feedback (optional)
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
