# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class FeedbackOut(UniversalBaseModel):
    id: str = pydantic.Field()
    """
    Unique feedback identifier (e.g. 'fb_abc123')
    """

    account_id: str = pydantic.Field()
    """
    Account that submitted this feedback
    """

    category: str = pydantic.Field()
    """
    Feedback type: 'bug', 'feature_request', 'difficulty', or 'feedback'
    """

    message: str = pydantic.Field()
    """
    Full feedback message
    """

    subject: typing.Optional[str] = pydantic.Field(default=None)
    """
    Short summary title
    """

    severity: str = pydantic.Field()
    """
    Impact level: 'low', 'normal', 'high', or 'critical'
    """

    agent_id: typing.Optional[str] = pydantic.Field(default=None)
    """
    Related AI agent ID, if any
    """

    contact_email: typing.Optional[str] = pydantic.Field(default=None)
    """
    Follow-up email, if provided
    """

    status: str = pydantic.Field()
    """
    Current status: 'open', 'acknowledged', 'in_progress', 'resolved', or 'closed'
    """

    created_at: dt.datetime = pydantic.Field()
    """
    When the feedback was submitted
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
