# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class KeylessAgentUpdate(UniversalBaseModel):
    """
    Partial agent update — only provided fields change (mirrors classic PATCH /v1/agents).
    """

    agent_name: typing.Optional[str] = None
    system_prompt: typing.Optional[str] = None
    initial_greeting: typing.Optional[str] = None
    voice_id: typing.Optional[str] = None
    transfer_number: typing.Optional[str] = None
    voicemail_message: typing.Optional[str] = None
    owner_phone: typing.Optional[str] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
