# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class KeylessEventsBody(UniversalBaseModel):
    """
    Optional POST body for polling events (GET works identically).
    """

    phone_number: typing.Optional[str] = None
    event_type: typing.Optional[str] = None
    limit: typing.Optional[int] = None
    lease_token: typing.Optional[str] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
