# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class KeylessListBody(UniversalBaseModel):
    """
    Optional POST body for listing numbers (GET works identically).
    """

    phone_number: typing.Optional[str] = pydantic.Field(default=None)
    """
    Filter to one owned number
    """

    lease_token: typing.Optional[str] = pydantic.Field(default=None)
    """
    agent_... or lease_... access token
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
