# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class KeylessBuyBody(UniversalBaseModel):
    agent_name: typing.Optional[str] = pydantic.Field(default=None)
    """
    Display name for the voice agent
    """

    system_prompt: typing.Optional[str] = pydantic.Field(default=None)
    """
    Personality/behavior instructions spoken on ALL calls
    """

    initial_greeting: typing.Optional[str] = pydantic.Field(default=None)
    """
    Opening line spoken when a call connects
    """

    voice_id: typing.Optional[str] = pydantic.Field(default=None)
    """
    TTS voice preset (e.g. 'female-1') or Cartesia UUID
    """

    transfer_number: typing.Optional[str] = pydantic.Field(default=None)
    """
    Must be the owner phone. Live transfers dial only owner_phone.
    """

    voicemail_message: typing.Optional[str] = pydantic.Field(default=None)
    """
    Message left if the call goes to voicemail
    """

    owner_phone: typing.Optional[str] = pydantic.Field(default=None)
    """
    Owner's E.164 phone. Calls from it enter task mode, and it is the only live-call transfer destination.
    """

    country: typing.Optional[str] = pydantic.Field(default=None)
    """
    Country code (only 'US' supported)
    """

    number_type: typing.Optional[str] = pydantic.Field(default=None)
    """
    'local' or 'tollfree'
    """

    area_code: typing.Optional[str] = pydantic.Field(default=None)
    """
    Preferred 3-digit US area code
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
