# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class KeylessWebhookBody(UniversalBaseModel):
    phone_number: str = pydantic.Field()
    """
    Your wallet-owned number whose agent gets the webhook
    """

    url: str = pydantic.Field()
    """
    HTTPS URL receiving the agent's events as signed JSON POSTs
    """

    secret: typing.Optional[str] = pydantic.Field(default=None)
    """
    HMAC signing secret (auto-generated if omitted)
    """

    signature_header: typing.Optional[str] = pydantic.Field(default=None)
    """
    HMAC header name (default 'X-Webhook-Signature')
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
