# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class KeylessCallBody(UniversalBaseModel):
    from_number: str = pydantic.Field()
    """
    Your wallet-owned number (E.164, e.g. '+12125551234')
    """

    to_number: str = pydantic.Field()
    """
    Destination phone number in E.164 format
    """

    lease_token: typing.Optional[str] = pydantic.Field(default=None)
    """
    lease_... token from numbers/buy. Calls bill prepaid credit; this endpoint does not take an x402 payment.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
