# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class PayDiscoveryBody(UniversalBaseModel):
    """
    Optional POST body for the discovery probe (GET works identically).
    """

    amount: typing.Optional[float] = pydantic.Field(default=None)
    """
    Top-up amount in USD to advertise requirements for.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
