# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class WebhookCreated(UniversalBaseModel):
    """
    Returned on POST — exposes the full secret this one time.
    """

    agent_id: str = pydantic.Field()
    """
    Agent this webhook is scoped to
    """

    url: str = pydantic.Field()
    """
    Configured webhook URL
    """

    secret: str = pydantic.Field()
    """
    Full signing secret. Save it now — it is masked on subsequent reads.
    """

    signature_header: str = pydantic.Field()
    """
    Header name used for HMAC-SHA256 signature delivery.
    """

    protocol: typing.Optional[str] = pydantic.Field(default=None)
    """
    Live relay protocol.
    """

    capabilities: typing.Optional[typing.Dict[str, typing.Any]] = pydantic.Field(default=None)
    """
    Declared relay v2 capabilities.
    """

    created_at: typing.Optional[dt.datetime] = pydantic.Field(default=None)
    """
    When the webhook was last (re)configured
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
