# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class WebhookCapabilities(UniversalBaseModel):
    """
    What a webhook runtime supports on live relay calls (protocol v2).
    """

    supports_amend: typing.Optional[bool] = pydantic.Field(default=None)
    """
    Accepts call.task.amend POSTs: caller follow-ups on the open task, same turn_id, higher revision. When false, AgentLine holds follow-ups and sends them as one merged task after the current one settles.
    """

    supports_cancel: typing.Optional[bool] = pydantic.Field(default=None)
    """
    Accepts call.task.cancel POSTs when the caller withdraws a task.
    """

    briefing: typing.Optional[bool] = pydantic.Field(default=None)
    """
    Accepts call.session.start at call start and pushes facts the caller is likely to need (disposition=facts, no turn_id).
    """

    streams_progress: typing.Optional[bool] = pydantic.Field(default=None)
    """
    Pushes partial/progress updates while it works.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
