# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from .raw_client import AsyncRawEventsClient, RawEventsClient


class EventsClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawEventsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawEventsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawEventsClient
        """
        return self._raw_client

    def poll(
        self,
        *,
        agent_id: typing.Optional[str] = None,
        event_type: typing.Optional[str] = None,
        limit: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> typing.Any:
        """
        Poll for telephony events from your AI agents.

        Returns pending events such as call completions, transcripts, and
        failures. Events are consumed on retrieval (one-time read) — once
        polled, they are automatically deleted from the mailbox.

        Your AI agent should call this endpoint periodically to receive
        notifications about completed calls and their transcripts.

        Filters:
          - agent_id: only events for a specific AI agent
          - event_type: e.g. "call.completed", "call.failed"

        Parameters
        ----------
        agent_id : typing.Optional[str]
            Filter events by AI agent ID

        event_type : typing.Optional[str]
            Filter by event type (e.g. 'call.completed', 'call.failed')

        limit : typing.Optional[int]
            Maximum number of events to return (1-200)

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Any
            Successful Response

        Examples
        --------
        from agentline_ai import AgentLine

        client = AgentLine(
            token="YOUR_TOKEN",
        )
        client.events.poll()
        """
        _response = self._raw_client.poll(
            agent_id=agent_id, event_type=event_type, limit=limit, request_options=request_options
        )
        return _response.data

    def peek(
        self,
        *,
        agent_id: typing.Optional[str] = None,
        limit: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> typing.Any:
        """
        Peek at pending telephony events without consuming them.

        Returns a preview of queued events (call completions, transcripts)
        without removing them from the mailbox. Useful for checking if
        there are events to process before committing to retrieve them.

        Parameters
        ----------
        agent_id : typing.Optional[str]
            Filter events by AI agent ID

        limit : typing.Optional[int]
            Maximum number of events to preview (1-200)

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Any
            Successful Response

        Examples
        --------
        from agentline_ai import AgentLine

        client = AgentLine(
            token="YOUR_TOKEN",
        )
        client.events.peek()
        """
        _response = self._raw_client.peek(agent_id=agent_id, limit=limit, request_options=request_options)
        return _response.data


class AsyncEventsClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawEventsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawEventsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawEventsClient
        """
        return self._raw_client

    async def poll(
        self,
        *,
        agent_id: typing.Optional[str] = None,
        event_type: typing.Optional[str] = None,
        limit: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> typing.Any:
        """
        Poll for telephony events from your AI agents.

        Returns pending events such as call completions, transcripts, and
        failures. Events are consumed on retrieval (one-time read) — once
        polled, they are automatically deleted from the mailbox.

        Your AI agent should call this endpoint periodically to receive
        notifications about completed calls and their transcripts.

        Filters:
          - agent_id: only events for a specific AI agent
          - event_type: e.g. "call.completed", "call.failed"

        Parameters
        ----------
        agent_id : typing.Optional[str]
            Filter events by AI agent ID

        event_type : typing.Optional[str]
            Filter by event type (e.g. 'call.completed', 'call.failed')

        limit : typing.Optional[int]
            Maximum number of events to return (1-200)

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Any
            Successful Response

        Examples
        --------
        import asyncio

        from agentline_ai import AsyncAgentLine

        client = AsyncAgentLine(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.events.poll()


        asyncio.run(main())
        """
        _response = await self._raw_client.poll(
            agent_id=agent_id, event_type=event_type, limit=limit, request_options=request_options
        )
        return _response.data

    async def peek(
        self,
        *,
        agent_id: typing.Optional[str] = None,
        limit: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> typing.Any:
        """
        Peek at pending telephony events without consuming them.

        Returns a preview of queued events (call completions, transcripts)
        without removing them from the mailbox. Useful for checking if
        there are events to process before committing to retrieve them.

        Parameters
        ----------
        agent_id : typing.Optional[str]
            Filter events by AI agent ID

        limit : typing.Optional[int]
            Maximum number of events to preview (1-200)

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Any
            Successful Response

        Examples
        --------
        import asyncio

        from agentline_ai import AsyncAgentLine

        client = AsyncAgentLine(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.events.peek()


        asyncio.run(main())
        """
        _response = await self._raw_client.peek(agent_id=agent_id, limit=limit, request_options=request_options)
        return _response.data
