# This file was auto-generated by Fern from our API Definition.

# isort: skip_file

import typing
from importlib import import_module

if typing.TYPE_CHECKING:
    from .types import (
        AgentOut,
        FeedbackCategory,
        FeedbackCreate,
        FeedbackOut,
        FeedbackSeverity,
        HttpValidationError,
        OtpRequest,
        TopupRequest,
        ValidationError,
        ValidationErrorLocItem,
        VerifyRequest,
        WebhookCreated,
    )
    from .errors import UnprocessableEntityError
    from . import agents, billing, calls, events, messages, numbers, voice, webhooks
    from ._default_clients import DefaultAioHttpClient, DefaultAsyncHttpxClient
    from .client import AgentLine, AsyncAgentLine
    from .environment import AgentLineEnvironment
    from .version import __version__
_dynamic_imports: typing.Dict[str, str] = {
    "AgentLine": ".client",
    "AgentLineEnvironment": ".environment",
    "AgentOut": ".types",
    "AsyncAgentLine": ".client",
    "DefaultAioHttpClient": "._default_clients",
    "DefaultAsyncHttpxClient": "._default_clients",
    "FeedbackCategory": ".types",
    "FeedbackCreate": ".types",
    "FeedbackOut": ".types",
    "FeedbackSeverity": ".types",
    "HttpValidationError": ".types",
    "OtpRequest": ".types",
    "TopupRequest": ".types",
    "UnprocessableEntityError": ".errors",
    "ValidationError": ".types",
    "ValidationErrorLocItem": ".types",
    "VerifyRequest": ".types",
    "WebhookCreated": ".types",
    "__version__": ".version",
    "agents": ".agents",
    "billing": ".billing",
    "calls": ".calls",
    "events": ".events",
    "messages": ".messages",
    "numbers": ".numbers",
    "voice": ".voice",
    "webhooks": ".webhooks",
}


def __getattr__(attr_name: str) -> typing.Any:
    module_name = _dynamic_imports.get(attr_name)
    if module_name is None:
        raise AttributeError(f"No {attr_name} found in _dynamic_imports for module name -> {__name__}")
    try:
        module = import_module(module_name, __package__)
        if module_name == f".{attr_name}":
            return module
        else:
            return getattr(module, attr_name)
    except ImportError as e:
        raise ImportError(f"Failed to import {attr_name} from {module_name}: {e}") from e
    except AttributeError as e:
        raise AttributeError(f"Failed to get {attr_name} from {module_name}: {e}") from e


def __dir__():
    lazy_attrs = list(_dynamic_imports.keys())
    return sorted(lazy_attrs)


__all__ = [
    "AgentLine",
    "AgentLineEnvironment",
    "AgentOut",
    "AsyncAgentLine",
    "DefaultAioHttpClient",
    "DefaultAsyncHttpxClient",
    "FeedbackCategory",
    "FeedbackCreate",
    "FeedbackOut",
    "FeedbackSeverity",
    "HttpValidationError",
    "OtpRequest",
    "TopupRequest",
    "UnprocessableEntityError",
    "ValidationError",
    "ValidationErrorLocItem",
    "VerifyRequest",
    "WebhookCreated",
    "__version__",
    "agents",
    "billing",
    "calls",
    "events",
    "messages",
    "numbers",
    "voice",
    "webhooks",
]
