# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from .raw_client import AsyncRawVoiceClient, RawVoiceClient

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class VoiceClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawVoiceClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawVoiceClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawVoiceClient
        """
        return self._raw_client

    def get(self, *, request_options: typing.Optional[RequestOptions] = None) -> typing.Any:
        """
        Get the current account-level default voice for AI phone agents.

        Returns which voice is used for all AI agents under this account
        unless overridden at the agent level or per-call. Controls how
        your AI agents sound during phone conversations.

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Any
            Successful Response

        Examples
        --------
        from agentline_ai import AgentLine

        client = AgentLine(
            token="YOUR_TOKEN",
        )
        client.voice.get()
        """
        _response = self._raw_client.get(request_options=request_options)
        return _response.data

    def reset(self, *, request_options: typing.Optional[RequestOptions] = None) -> typing.Any:
        """
        Reset account voice to the system default.

        Removes the account-level voice override so all AI agents fall back
        to the system default voice during phone calls (unless they have
        their own voice_id configured).

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Any
            Successful Response

        Examples
        --------
        from agentline_ai import AgentLine

        client = AgentLine(
            token="YOUR_TOKEN",
        )
        client.voice.reset()
        """
        _response = self._raw_client.reset(request_options=request_options)
        return _response.data

    def set(self, *, voice_id: str, request_options: typing.Optional[RequestOptions] = None) -> typing.Any:
        """
        Set the account-level default voice for AI phone agents.

        This becomes the default voice for ALL AI agents under this account,
        controlling how they sound on phone calls. Individual agents or
        specific calls can still override this setting.

        Voice resolution priority:
          1. Per-call voice_id (POST /v1/calls)
          2. Agent voice_id (PATCH /v1/agents/{id})
          3. Account default (this endpoint)  ← you are here
          4. System default (Supportive Male)

        Accepts:
          - A preset name: "female-1", "female-2", "female-3", "male-1", "male-2", "male-3"
          - A Cartesia voice UUID: "f786b574-daa5-4673-aa0c-cbe3e8534c02"

        Parameters
        ----------
        voice_id : str
            TTS voice preset name (e.g. 'female-1', 'male-1') or Cartesia voice UUID

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Any
            Successful Response

        Examples
        --------
        from agentline_ai import AgentLine

        client = AgentLine(
            token="YOUR_TOKEN",
        )
        client.voice.set(
            voice_id="voice_id",
        )
        """
        _response = self._raw_client.set(voice_id=voice_id, request_options=request_options)
        return _response.data

    def list(self, *, request_options: typing.Optional[RequestOptions] = None) -> typing.Any:
        """
        List all available voice presets for AI phone agents.

        Returns named TTS (text-to-speech) voice presets that can be used
        when configuring AI agents or making phone calls. Each voice defines
        how your AI agent sounds on the phone.

        You can use a preset name (e.g. "female-1", "male-1") or pass any
        valid Cartesia voice UUID directly as a voice_id.

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Any
            Successful Response

        Examples
        --------
        from agentline_ai import AgentLine

        client = AgentLine(
            token="YOUR_TOKEN",
        )
        client.voice.list()
        """
        _response = self._raw_client.list(request_options=request_options)
        return _response.data


class AsyncVoiceClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawVoiceClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawVoiceClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawVoiceClient
        """
        return self._raw_client

    async def get(self, *, request_options: typing.Optional[RequestOptions] = None) -> typing.Any:
        """
        Get the current account-level default voice for AI phone agents.

        Returns which voice is used for all AI agents under this account
        unless overridden at the agent level or per-call. Controls how
        your AI agents sound during phone conversations.

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Any
            Successful Response

        Examples
        --------
        import asyncio

        from agentline_ai import AsyncAgentLine

        client = AsyncAgentLine(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.voice.get()


        asyncio.run(main())
        """
        _response = await self._raw_client.get(request_options=request_options)
        return _response.data

    async def reset(self, *, request_options: typing.Optional[RequestOptions] = None) -> typing.Any:
        """
        Reset account voice to the system default.

        Removes the account-level voice override so all AI agents fall back
        to the system default voice during phone calls (unless they have
        their own voice_id configured).

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Any
            Successful Response

        Examples
        --------
        import asyncio

        from agentline_ai import AsyncAgentLine

        client = AsyncAgentLine(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.voice.reset()


        asyncio.run(main())
        """
        _response = await self._raw_client.reset(request_options=request_options)
        return _response.data

    async def set(self, *, voice_id: str, request_options: typing.Optional[RequestOptions] = None) -> typing.Any:
        """
        Set the account-level default voice for AI phone agents.

        This becomes the default voice for ALL AI agents under this account,
        controlling how they sound on phone calls. Individual agents or
        specific calls can still override this setting.

        Voice resolution priority:
          1. Per-call voice_id (POST /v1/calls)
          2. Agent voice_id (PATCH /v1/agents/{id})
          3. Account default (this endpoint)  ← you are here
          4. System default (Supportive Male)

        Accepts:
          - A preset name: "female-1", "female-2", "female-3", "male-1", "male-2", "male-3"
          - A Cartesia voice UUID: "f786b574-daa5-4673-aa0c-cbe3e8534c02"

        Parameters
        ----------
        voice_id : str
            TTS voice preset name (e.g. 'female-1', 'male-1') or Cartesia voice UUID

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Any
            Successful Response

        Examples
        --------
        import asyncio

        from agentline_ai import AsyncAgentLine

        client = AsyncAgentLine(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.voice.set(
                voice_id="voice_id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.set(voice_id=voice_id, request_options=request_options)
        return _response.data

    async def list(self, *, request_options: typing.Optional[RequestOptions] = None) -> typing.Any:
        """
        List all available voice presets for AI phone agents.

        Returns named TTS (text-to-speech) voice presets that can be used
        when configuring AI agents or making phone calls. Each voice defines
        how your AI agent sounds on the phone.

        You can use a preset name (e.g. "female-1", "male-1") or pass any
        valid Cartesia voice UUID directly as a voice_id.

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Any
            Successful Response

        Examples
        --------
        import asyncio

        from agentline_ai import AsyncAgentLine

        client = AsyncAgentLine(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.voice.list()


        asyncio.run(main())
        """
        _response = await self._raw_client.list(request_options=request_options)
        return _response.data
