# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.agent_out import AgentOut
from .raw_client import AsyncRawAgentsClient, RawAgentsClient

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class AgentsClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawAgentsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawAgentsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawAgentsClient
        """
        return self._raw_client

    def list(self, *, request_options: typing.Optional[RequestOptions] = None) -> typing.Any:
        """
        List all AI voice agents configured on your account.

        Returns every AI phone agent you've created, including their
        system prompts, voice settings, and associated phone numbers.
        Useful for checking which agents are ready to make or receive calls.

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Any
            Successful Response

        Examples
        --------
        from agentline_ai import AgentLine

        client = AgentLine(
            token="YOUR_TOKEN",
        )
        client.agents.list()
        """
        _response = self._raw_client.list(request_options=request_options)
        return _response.data

    def create(
        self,
        *,
        name: str,
        system_prompt: typing.Optional[str] = OMIT,
        initial_greeting: typing.Optional[str] = OMIT,
        voice_id: typing.Optional[str] = OMIT,
        transfer_number: typing.Optional[str] = OMIT,
        voicemail_message: typing.Optional[str] = OMIT,
        owner_phone: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AgentOut:
        """
        Create a new AI voice agent for telephony.

        Sets up a new AI phone agent with a custom system prompt, voice,
        and greeting. Once created, buy a phone number and attach it to
        this agent so it can make and receive calls autonomously.

        Fields:
          - name: Display name for the agent
          - system_prompt: Instructions that define the agent's personality and behavior on calls
          - initial_greeting: What the AI agent says when the call connects
          - voice_id: TTS voice preset (e.g. "female-1") or Cartesia UUID
          - transfer_number: Phone number to transfer calls to (e.g. a human operator)
          - voicemail_message: Message the agent leaves if the call goes to voicemail

        Parameters
        ----------
        name : str
            Display name for the AI voice agent

        system_prompt : typing.Optional[str]
            Default instructions for the agent's personality and behavior on ALL calls (inbound and outbound). Can be overridden per-call via POST /v1/calls.

        initial_greeting : typing.Optional[str]
            Default opening line spoken on ALL calls (inbound and outbound), e.g. 'Hello, how can I help you today?'. Can be overridden per-call via POST /v1/calls.

        voice_id : typing.Optional[str]
            TTS voice preset name (e.g. 'female-1', 'male-1') or Cartesia voice UUID; defaults to system voice if not set

        transfer_number : typing.Optional[str]
            Phone number in E.164 format to transfer calls to (e.g. a human operator fallback)

        voicemail_message : typing.Optional[str]
            Message the AI agent leaves if the call goes to voicemail

        owner_phone : typing.Optional[str]
            Owner's phone number in E.164 format (e.g. '+12125551234'). Calls from this number enter task mode — the agent treats speech as executable instructions.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AgentOut
            Successful Response

        Examples
        --------
        from agentline_ai import AgentLine

        client = AgentLine(
            token="YOUR_TOKEN",
        )
        client.agents.create(
            name="name",
        )
        """
        _response = self._raw_client.create(
            name=name,
            system_prompt=system_prompt,
            initial_greeting=initial_greeting,
            voice_id=voice_id,
            transfer_number=transfer_number,
            voicemail_message=voicemail_message,
            owner_phone=owner_phone,
            request_options=request_options,
        )
        return _response.data

    def get(self, agent_id: str, *, request_options: typing.Optional[RequestOptions] = None) -> typing.Any:
        """
        Get details of a specific AI voice agent.

        Returns the agent's full configuration including system prompt,
        voice settings, greeting, and transfer number.

        Parameters
        ----------
        agent_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Any
            Successful Response

        Examples
        --------
        from agentline_ai import AgentLine

        client = AgentLine(
            token="YOUR_TOKEN",
        )
        client.agents.get(
            agent_id="agent_id",
        )
        """
        _response = self._raw_client.get(agent_id, request_options=request_options)
        return _response.data

    def delete(self, agent_id: str, *, request_options: typing.Optional[RequestOptions] = None) -> typing.Any:
        """
        Delete an AI voice agent.

        Permanently removes the agent and detaches any phone numbers
        assigned to it. Detached numbers remain active on your account
        and can be reassigned to another agent.

        Parameters
        ----------
        agent_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Any
            Successful Response

        Examples
        --------
        from agentline_ai import AgentLine

        client = AgentLine(
            token="YOUR_TOKEN",
        )
        client.agents.delete(
            agent_id="agent_id",
        )
        """
        _response = self._raw_client.delete(agent_id, request_options=request_options)
        return _response.data

    def update(
        self,
        agent_id: str,
        *,
        name: typing.Optional[str] = OMIT,
        system_prompt: typing.Optional[str] = OMIT,
        initial_greeting: typing.Optional[str] = OMIT,
        voice_id: typing.Optional[str] = OMIT,
        transfer_number: typing.Optional[str] = OMIT,
        voicemail_message: typing.Optional[str] = OMIT,
        owner_phone: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> typing.Any:
        """
        Update an AI voice agent's configuration.

        Modify any combination of the agent's settings: system prompt,
        voice, greeting, transfer number, or voicemail message.
        Changes take effect on the next call the agent handles.
        Only include the fields you want to change — unset fields are preserved.

        Parameters
        ----------
        agent_id : str

        name : typing.Optional[str]
            New display name for the AI voice agent

        system_prompt : typing.Optional[str]
            Updated default instructions for ALL future calls (does not affect calls already in progress)

        initial_greeting : typing.Optional[str]
            Updated default greeting for ALL future calls (inbound and outbound)

        voice_id : typing.Optional[str]
            New TTS voice preset name or Cartesia voice UUID

        transfer_number : typing.Optional[str]
            Updated transfer phone number in E.164 format

        voicemail_message : typing.Optional[str]
            Updated voicemail message

        owner_phone : typing.Optional[str]
            Updated owner phone number in E.164 format for task mode

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Any
            Successful Response

        Examples
        --------
        from agentline_ai import AgentLine

        client = AgentLine(
            token="YOUR_TOKEN",
        )
        client.agents.update(
            agent_id="agent_id",
        )
        """
        _response = self._raw_client.update(
            agent_id,
            name=name,
            system_prompt=system_prompt,
            initial_greeting=initial_greeting,
            voice_id=voice_id,
            transfer_number=transfer_number,
            voicemail_message=voicemail_message,
            owner_phone=owner_phone,
            request_options=request_options,
        )
        return _response.data


class AsyncAgentsClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawAgentsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawAgentsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawAgentsClient
        """
        return self._raw_client

    async def list(self, *, request_options: typing.Optional[RequestOptions] = None) -> typing.Any:
        """
        List all AI voice agents configured on your account.

        Returns every AI phone agent you've created, including their
        system prompts, voice settings, and associated phone numbers.
        Useful for checking which agents are ready to make or receive calls.

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Any
            Successful Response

        Examples
        --------
        import asyncio

        from agentline_ai import AsyncAgentLine

        client = AsyncAgentLine(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.agents.list()


        asyncio.run(main())
        """
        _response = await self._raw_client.list(request_options=request_options)
        return _response.data

    async def create(
        self,
        *,
        name: str,
        system_prompt: typing.Optional[str] = OMIT,
        initial_greeting: typing.Optional[str] = OMIT,
        voice_id: typing.Optional[str] = OMIT,
        transfer_number: typing.Optional[str] = OMIT,
        voicemail_message: typing.Optional[str] = OMIT,
        owner_phone: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AgentOut:
        """
        Create a new AI voice agent for telephony.

        Sets up a new AI phone agent with a custom system prompt, voice,
        and greeting. Once created, buy a phone number and attach it to
        this agent so it can make and receive calls autonomously.

        Fields:
          - name: Display name for the agent
          - system_prompt: Instructions that define the agent's personality and behavior on calls
          - initial_greeting: What the AI agent says when the call connects
          - voice_id: TTS voice preset (e.g. "female-1") or Cartesia UUID
          - transfer_number: Phone number to transfer calls to (e.g. a human operator)
          - voicemail_message: Message the agent leaves if the call goes to voicemail

        Parameters
        ----------
        name : str
            Display name for the AI voice agent

        system_prompt : typing.Optional[str]
            Default instructions for the agent's personality and behavior on ALL calls (inbound and outbound). Can be overridden per-call via POST /v1/calls.

        initial_greeting : typing.Optional[str]
            Default opening line spoken on ALL calls (inbound and outbound), e.g. 'Hello, how can I help you today?'. Can be overridden per-call via POST /v1/calls.

        voice_id : typing.Optional[str]
            TTS voice preset name (e.g. 'female-1', 'male-1') or Cartesia voice UUID; defaults to system voice if not set

        transfer_number : typing.Optional[str]
            Phone number in E.164 format to transfer calls to (e.g. a human operator fallback)

        voicemail_message : typing.Optional[str]
            Message the AI agent leaves if the call goes to voicemail

        owner_phone : typing.Optional[str]
            Owner's phone number in E.164 format (e.g. '+12125551234'). Calls from this number enter task mode — the agent treats speech as executable instructions.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AgentOut
            Successful Response

        Examples
        --------
        import asyncio

        from agentline_ai import AsyncAgentLine

        client = AsyncAgentLine(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.agents.create(
                name="name",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.create(
            name=name,
            system_prompt=system_prompt,
            initial_greeting=initial_greeting,
            voice_id=voice_id,
            transfer_number=transfer_number,
            voicemail_message=voicemail_message,
            owner_phone=owner_phone,
            request_options=request_options,
        )
        return _response.data

    async def get(self, agent_id: str, *, request_options: typing.Optional[RequestOptions] = None) -> typing.Any:
        """
        Get details of a specific AI voice agent.

        Returns the agent's full configuration including system prompt,
        voice settings, greeting, and transfer number.

        Parameters
        ----------
        agent_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Any
            Successful Response

        Examples
        --------
        import asyncio

        from agentline_ai import AsyncAgentLine

        client = AsyncAgentLine(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.agents.get(
                agent_id="agent_id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get(agent_id, request_options=request_options)
        return _response.data

    async def delete(self, agent_id: str, *, request_options: typing.Optional[RequestOptions] = None) -> typing.Any:
        """
        Delete an AI voice agent.

        Permanently removes the agent and detaches any phone numbers
        assigned to it. Detached numbers remain active on your account
        and can be reassigned to another agent.

        Parameters
        ----------
        agent_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Any
            Successful Response

        Examples
        --------
        import asyncio

        from agentline_ai import AsyncAgentLine

        client = AsyncAgentLine(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.agents.delete(
                agent_id="agent_id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.delete(agent_id, request_options=request_options)
        return _response.data

    async def update(
        self,
        agent_id: str,
        *,
        name: typing.Optional[str] = OMIT,
        system_prompt: typing.Optional[str] = OMIT,
        initial_greeting: typing.Optional[str] = OMIT,
        voice_id: typing.Optional[str] = OMIT,
        transfer_number: typing.Optional[str] = OMIT,
        voicemail_message: typing.Optional[str] = OMIT,
        owner_phone: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> typing.Any:
        """
        Update an AI voice agent's configuration.

        Modify any combination of the agent's settings: system prompt,
        voice, greeting, transfer number, or voicemail message.
        Changes take effect on the next call the agent handles.
        Only include the fields you want to change — unset fields are preserved.

        Parameters
        ----------
        agent_id : str

        name : typing.Optional[str]
            New display name for the AI voice agent

        system_prompt : typing.Optional[str]
            Updated default instructions for ALL future calls (does not affect calls already in progress)

        initial_greeting : typing.Optional[str]
            Updated default greeting for ALL future calls (inbound and outbound)

        voice_id : typing.Optional[str]
            New TTS voice preset name or Cartesia voice UUID

        transfer_number : typing.Optional[str]
            Updated transfer phone number in E.164 format

        voicemail_message : typing.Optional[str]
            Updated voicemail message

        owner_phone : typing.Optional[str]
            Updated owner phone number in E.164 format for task mode

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Any
            Successful Response

        Examples
        --------
        import asyncio

        from agentline_ai import AsyncAgentLine

        client = AsyncAgentLine(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.agents.update(
                agent_id="agent_id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.update(
            agent_id,
            name=name,
            system_prompt=system_prompt,
            initial_greeting=initial_greeting,
            voice_id=voice_id,
            transfer_number=transfer_number,
            voicemail_message=voicemail_message,
            owner_phone=owner_phone,
            request_options=request_options,
        )
        return _response.data
