# This file was auto-generated by Fern from our API Definition.

import typing
from json.decoder import JSONDecodeError

from ..core.api_error import ApiError
from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.http_response import AsyncHttpResponse, HttpResponse
from ..core.jsonable_encoder import encode_path_param
from ..core.parse_error import ParsingError
from ..core.pydantic_utilities import parse_obj_as
from ..core.request_options import RequestOptions
from ..errors.unprocessable_entity_error import UnprocessableEntityError
from ..types.agent_out import AgentOut
from ..types.http_validation_error import HttpValidationError
from pydantic import ValidationError

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class RawAgentsClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._client_wrapper = client_wrapper

    def list(self, *, request_options: typing.Optional[RequestOptions] = None) -> HttpResponse[typing.Any]:
        """
        List all AI voice agents configured on your account.

        Returns every AI phone agent you've created, including their
        system prompts, voice settings, and associated phone numbers.
        Useful for checking which agents are ready to make or receive calls.

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[typing.Any]
            Successful Response
        """
        _response = self._client_wrapper.httpx_client.request(
            "v1/agents",
            method="GET",
            request_options=request_options,
        )
        try:
            if _response is None or not _response.text.strip():
                return HttpResponse(response=_response, data=None)
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    typing.Any,
                    parse_obj_as(
                        type_=typing.Any,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def create(
        self,
        *,
        name: str,
        system_prompt: typing.Optional[str] = OMIT,
        initial_greeting: typing.Optional[str] = OMIT,
        voice_id: typing.Optional[str] = OMIT,
        transfer_number: typing.Optional[str] = OMIT,
        voicemail_message: typing.Optional[str] = OMIT,
        owner_phone: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[AgentOut]:
        """
        Create a new AI voice agent for telephony.

        Sets up a new AI phone agent with a custom system prompt, voice,
        and greeting. Once created, buy a phone number and attach it to
        this agent so it can make and receive calls autonomously.

        Fields:
          - name: Display name for the agent
          - system_prompt: Instructions that define the agent's personality and behavior on calls
          - initial_greeting: What the AI agent says when the call connects
          - voice_id: TTS voice preset (e.g. "female-1") or Cartesia UUID
          - transfer_number: Phone number to transfer calls to (e.g. a human operator)
          - voicemail_message: Message the agent leaves if the call goes to voicemail

        Parameters
        ----------
        name : str
            Display name for the AI voice agent

        system_prompt : typing.Optional[str]
            Default instructions for the agent's personality and behavior on ALL calls (inbound and outbound). Can be overridden per-call via POST /v1/calls.

        initial_greeting : typing.Optional[str]
            Default opening line spoken on ALL calls (inbound and outbound), e.g. 'Hello, how can I help you today?'. Can be overridden per-call via POST /v1/calls.

        voice_id : typing.Optional[str]
            TTS voice preset name (e.g. 'female-1', 'male-1') or Cartesia voice UUID; defaults to system voice if not set

        transfer_number : typing.Optional[str]
            Phone number in E.164 format to transfer calls to (e.g. a human operator fallback)

        voicemail_message : typing.Optional[str]
            Message the AI agent leaves if the call goes to voicemail

        owner_phone : typing.Optional[str]
            Owner's phone number in E.164 format (e.g. '+12125551234'). Calls from this number enter task mode — the agent treats speech as executable instructions.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[AgentOut]
            Successful Response
        """
        _response = self._client_wrapper.httpx_client.request(
            "v1/agents",
            method="POST",
            json={
                "name": name,
                "system_prompt": system_prompt,
                "initial_greeting": initial_greeting,
                "voice_id": voice_id,
                "transfer_number": transfer_number,
                "voicemail_message": voicemail_message,
                "owner_phone": owner_phone,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    AgentOut,
                    parse_obj_as(
                        type_=AgentOut,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        HttpValidationError,
                        parse_obj_as(
                            type_=HttpValidationError,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def get(
        self, agent_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> HttpResponse[typing.Any]:
        """
        Get details of a specific AI voice agent.

        Returns the agent's full configuration including system prompt,
        voice settings, greeting, and transfer number.

        Parameters
        ----------
        agent_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[typing.Any]
            Successful Response
        """
        _response = self._client_wrapper.httpx_client.request(
            f"v1/agents/{encode_path_param(agent_id)}",
            method="GET",
            request_options=request_options,
        )
        try:
            if _response is None or not _response.text.strip():
                return HttpResponse(response=_response, data=None)
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    typing.Any,
                    parse_obj_as(
                        type_=typing.Any,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        HttpValidationError,
                        parse_obj_as(
                            type_=HttpValidationError,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def delete(
        self, agent_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> HttpResponse[typing.Any]:
        """
        Delete an AI voice agent.

        Permanently removes the agent and detaches any phone numbers
        assigned to it. Detached numbers remain active on your account
        and can be reassigned to another agent.

        Parameters
        ----------
        agent_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[typing.Any]
            Successful Response
        """
        _response = self._client_wrapper.httpx_client.request(
            f"v1/agents/{encode_path_param(agent_id)}",
            method="DELETE",
            request_options=request_options,
        )
        try:
            if _response is None or not _response.text.strip():
                return HttpResponse(response=_response, data=None)
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    typing.Any,
                    parse_obj_as(
                        type_=typing.Any,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        HttpValidationError,
                        parse_obj_as(
                            type_=HttpValidationError,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def update(
        self,
        agent_id: str,
        *,
        name: typing.Optional[str] = OMIT,
        system_prompt: typing.Optional[str] = OMIT,
        initial_greeting: typing.Optional[str] = OMIT,
        voice_id: typing.Optional[str] = OMIT,
        transfer_number: typing.Optional[str] = OMIT,
        voicemail_message: typing.Optional[str] = OMIT,
        owner_phone: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[typing.Any]:
        """
        Update an AI voice agent's configuration.

        Modify any combination of the agent's settings: system prompt,
        voice, greeting, transfer number, or voicemail message.
        Changes take effect on the next call the agent handles.
        Only include the fields you want to change — unset fields are preserved.

        Parameters
        ----------
        agent_id : str

        name : typing.Optional[str]
            New display name for the AI voice agent

        system_prompt : typing.Optional[str]
            Updated default instructions for ALL future calls (does not affect calls already in progress)

        initial_greeting : typing.Optional[str]
            Updated default greeting for ALL future calls (inbound and outbound)

        voice_id : typing.Optional[str]
            New TTS voice preset name or Cartesia voice UUID

        transfer_number : typing.Optional[str]
            Updated transfer phone number in E.164 format

        voicemail_message : typing.Optional[str]
            Updated voicemail message

        owner_phone : typing.Optional[str]
            Updated owner phone number in E.164 format for task mode

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[typing.Any]
            Successful Response
        """
        _response = self._client_wrapper.httpx_client.request(
            f"v1/agents/{encode_path_param(agent_id)}",
            method="PATCH",
            json={
                "name": name,
                "system_prompt": system_prompt,
                "initial_greeting": initial_greeting,
                "voice_id": voice_id,
                "transfer_number": transfer_number,
                "voicemail_message": voicemail_message,
                "owner_phone": owner_phone,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if _response is None or not _response.text.strip():
                return HttpResponse(response=_response, data=None)
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    typing.Any,
                    parse_obj_as(
                        type_=typing.Any,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        HttpValidationError,
                        parse_obj_as(
                            type_=HttpValidationError,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)


class AsyncRawAgentsClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._client_wrapper = client_wrapper

    async def list(self, *, request_options: typing.Optional[RequestOptions] = None) -> AsyncHttpResponse[typing.Any]:
        """
        List all AI voice agents configured on your account.

        Returns every AI phone agent you've created, including their
        system prompts, voice settings, and associated phone numbers.
        Useful for checking which agents are ready to make or receive calls.

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[typing.Any]
            Successful Response
        """
        _response = await self._client_wrapper.httpx_client.request(
            "v1/agents",
            method="GET",
            request_options=request_options,
        )
        try:
            if _response is None or not _response.text.strip():
                return AsyncHttpResponse(response=_response, data=None)
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    typing.Any,
                    parse_obj_as(
                        type_=typing.Any,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def create(
        self,
        *,
        name: str,
        system_prompt: typing.Optional[str] = OMIT,
        initial_greeting: typing.Optional[str] = OMIT,
        voice_id: typing.Optional[str] = OMIT,
        transfer_number: typing.Optional[str] = OMIT,
        voicemail_message: typing.Optional[str] = OMIT,
        owner_phone: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[AgentOut]:
        """
        Create a new AI voice agent for telephony.

        Sets up a new AI phone agent with a custom system prompt, voice,
        and greeting. Once created, buy a phone number and attach it to
        this agent so it can make and receive calls autonomously.

        Fields:
          - name: Display name for the agent
          - system_prompt: Instructions that define the agent's personality and behavior on calls
          - initial_greeting: What the AI agent says when the call connects
          - voice_id: TTS voice preset (e.g. "female-1") or Cartesia UUID
          - transfer_number: Phone number to transfer calls to (e.g. a human operator)
          - voicemail_message: Message the agent leaves if the call goes to voicemail

        Parameters
        ----------
        name : str
            Display name for the AI voice agent

        system_prompt : typing.Optional[str]
            Default instructions for the agent's personality and behavior on ALL calls (inbound and outbound). Can be overridden per-call via POST /v1/calls.

        initial_greeting : typing.Optional[str]
            Default opening line spoken on ALL calls (inbound and outbound), e.g. 'Hello, how can I help you today?'. Can be overridden per-call via POST /v1/calls.

        voice_id : typing.Optional[str]
            TTS voice preset name (e.g. 'female-1', 'male-1') or Cartesia voice UUID; defaults to system voice if not set

        transfer_number : typing.Optional[str]
            Phone number in E.164 format to transfer calls to (e.g. a human operator fallback)

        voicemail_message : typing.Optional[str]
            Message the AI agent leaves if the call goes to voicemail

        owner_phone : typing.Optional[str]
            Owner's phone number in E.164 format (e.g. '+12125551234'). Calls from this number enter task mode — the agent treats speech as executable instructions.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[AgentOut]
            Successful Response
        """
        _response = await self._client_wrapper.httpx_client.request(
            "v1/agents",
            method="POST",
            json={
                "name": name,
                "system_prompt": system_prompt,
                "initial_greeting": initial_greeting,
                "voice_id": voice_id,
                "transfer_number": transfer_number,
                "voicemail_message": voicemail_message,
                "owner_phone": owner_phone,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    AgentOut,
                    parse_obj_as(
                        type_=AgentOut,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        HttpValidationError,
                        parse_obj_as(
                            type_=HttpValidationError,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def get(
        self, agent_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> AsyncHttpResponse[typing.Any]:
        """
        Get details of a specific AI voice agent.

        Returns the agent's full configuration including system prompt,
        voice settings, greeting, and transfer number.

        Parameters
        ----------
        agent_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[typing.Any]
            Successful Response
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"v1/agents/{encode_path_param(agent_id)}",
            method="GET",
            request_options=request_options,
        )
        try:
            if _response is None or not _response.text.strip():
                return AsyncHttpResponse(response=_response, data=None)
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    typing.Any,
                    parse_obj_as(
                        type_=typing.Any,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        HttpValidationError,
                        parse_obj_as(
                            type_=HttpValidationError,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def delete(
        self, agent_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> AsyncHttpResponse[typing.Any]:
        """
        Delete an AI voice agent.

        Permanently removes the agent and detaches any phone numbers
        assigned to it. Detached numbers remain active on your account
        and can be reassigned to another agent.

        Parameters
        ----------
        agent_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[typing.Any]
            Successful Response
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"v1/agents/{encode_path_param(agent_id)}",
            method="DELETE",
            request_options=request_options,
        )
        try:
            if _response is None or not _response.text.strip():
                return AsyncHttpResponse(response=_response, data=None)
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    typing.Any,
                    parse_obj_as(
                        type_=typing.Any,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        HttpValidationError,
                        parse_obj_as(
                            type_=HttpValidationError,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def update(
        self,
        agent_id: str,
        *,
        name: typing.Optional[str] = OMIT,
        system_prompt: typing.Optional[str] = OMIT,
        initial_greeting: typing.Optional[str] = OMIT,
        voice_id: typing.Optional[str] = OMIT,
        transfer_number: typing.Optional[str] = OMIT,
        voicemail_message: typing.Optional[str] = OMIT,
        owner_phone: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[typing.Any]:
        """
        Update an AI voice agent's configuration.

        Modify any combination of the agent's settings: system prompt,
        voice, greeting, transfer number, or voicemail message.
        Changes take effect on the next call the agent handles.
        Only include the fields you want to change — unset fields are preserved.

        Parameters
        ----------
        agent_id : str

        name : typing.Optional[str]
            New display name for the AI voice agent

        system_prompt : typing.Optional[str]
            Updated default instructions for ALL future calls (does not affect calls already in progress)

        initial_greeting : typing.Optional[str]
            Updated default greeting for ALL future calls (inbound and outbound)

        voice_id : typing.Optional[str]
            New TTS voice preset name or Cartesia voice UUID

        transfer_number : typing.Optional[str]
            Updated transfer phone number in E.164 format

        voicemail_message : typing.Optional[str]
            Updated voicemail message

        owner_phone : typing.Optional[str]
            Updated owner phone number in E.164 format for task mode

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[typing.Any]
            Successful Response
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"v1/agents/{encode_path_param(agent_id)}",
            method="PATCH",
            json={
                "name": name,
                "system_prompt": system_prompt,
                "initial_greeting": initial_greeting,
                "voice_id": voice_id,
                "transfer_number": transfer_number,
                "voicemail_message": voicemail_message,
                "owner_phone": owner_phone,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if _response is None or not _response.text.strip():
                return AsyncHttpResponse(response=_response, data=None)
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    typing.Any,
                    parse_obj_as(
                        type_=typing.Any,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        HttpValidationError,
                        parse_obj_as(
                            type_=HttpValidationError,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)
