# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from .raw_client import AsyncRawBillingClient, RawBillingClient


class BillingClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawBillingClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawBillingClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawBillingClient
        """
        return self._raw_client

    def get_balance(self, *, request_options: typing.Optional[RequestOptions] = None) -> typing.Any:
        """
        Get your AI telephony account balance and rate card.

        Returns the current balance, currency, billing rates for calls
        and phone numbers, and how many call minutes or phone numbers
        the balance can cover. Use this to check affordability before
        making calls or buying numbers for your AI agents.

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Any
            Successful Response

        Examples
        --------
        from agentline_ai import AgentLine

        client = AgentLine(
            api_key="YOUR_API_KEY",
        )
        client.billing.get_balance()
        """
        _response = self._raw_client.get_balance(request_options=request_options)
        return _response.data

    def get_expenditure(
        self, *, period: typing.Optional[str] = None, request_options: typing.Optional[RequestOptions] = None
    ) -> typing.Any:
        """
        Get a detailed expenditure breakdown for AI telephony usage.

        Shows total spend split by category (voice calls, phone number
        provisioning, top-ups, refunds) with counts and averages.
        Useful for tracking how much your AI agents are spending on
        phone calls and phone numbers.

        Parameters
        ----------
        period : typing.Optional[str]
            Time period: 'current_month', 'last_month', 'all_time', or 'YYYY-MM'

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Any
            Successful Response

        Examples
        --------
        from agentline_ai import AgentLine

        client = AgentLine(
            api_key="YOUR_API_KEY",
        )
        client.billing.get_expenditure()
        """
        _response = self._raw_client.get_expenditure(period=period, request_options=request_options)
        return _response.data

    def list_call_charges(
        self,
        *,
        limit: typing.Optional[int] = None,
        offset: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> typing.Any:
        """
        List individual call charges from AI agent phone calls.

        Each entry includes the voice call duration, cost, direction
        (inbound/outbound), phone numbers involved, and timestamp.
        Shows exactly how much each AI agent call cost.

        Parameters
        ----------
        limit : typing.Optional[int]
            Maximum number of call charges to return (1-200)

        offset : typing.Optional[int]
            Number of records to skip for pagination

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Any
            Successful Response

        Examples
        --------
        from agentline_ai import AgentLine

        client = AgentLine(
            api_key="YOUR_API_KEY",
        )
        client.billing.list_call_charges()
        """
        _response = self._raw_client.list_call_charges(limit=limit, offset=offset, request_options=request_options)
        return _response.data

    def list_number_charges(
        self,
        *,
        limit: typing.Optional[int] = None,
        offset: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> typing.Any:
        """
        List phone number provisioning charges.

        Shows the cost of each phone number bought for your AI agents,
        including the number, country, and current status.

        Parameters
        ----------
        limit : typing.Optional[int]
            Maximum number of number charges to return (1-200)

        offset : typing.Optional[int]
            Number of records to skip for pagination

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Any
            Successful Response

        Examples
        --------
        from agentline_ai import AgentLine

        client = AgentLine(
            api_key="YOUR_API_KEY",
        )
        client.billing.list_number_charges()
        """
        _response = self._raw_client.list_number_charges(limit=limit, offset=offset, request_options=request_options)
        return _response.data

    def get_summary(
        self, *, months: typing.Optional[int] = None, request_options: typing.Optional[RequestOptions] = None
    ) -> typing.Any:
        """
        Month-over-month spending summary.

        Returns total debits grouped by month for trend analysis.

        Parameters
        ----------
        months : typing.Optional[int]
            Number of months to show

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Any
            Successful Response

        Examples
        --------
        from agentline_ai import AgentLine

        client = AgentLine(
            api_key="YOUR_API_KEY",
        )
        client.billing.get_summary()
        """
        _response = self._raw_client.get_summary(months=months, request_options=request_options)
        return _response.data


class AsyncBillingClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawBillingClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawBillingClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawBillingClient
        """
        return self._raw_client

    async def get_balance(self, *, request_options: typing.Optional[RequestOptions] = None) -> typing.Any:
        """
        Get your AI telephony account balance and rate card.

        Returns the current balance, currency, billing rates for calls
        and phone numbers, and how many call minutes or phone numbers
        the balance can cover. Use this to check affordability before
        making calls or buying numbers for your AI agents.

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Any
            Successful Response

        Examples
        --------
        import asyncio

        from agentline_ai import AsyncAgentLine

        client = AsyncAgentLine(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.billing.get_balance()


        asyncio.run(main())
        """
        _response = await self._raw_client.get_balance(request_options=request_options)
        return _response.data

    async def get_expenditure(
        self, *, period: typing.Optional[str] = None, request_options: typing.Optional[RequestOptions] = None
    ) -> typing.Any:
        """
        Get a detailed expenditure breakdown for AI telephony usage.

        Shows total spend split by category (voice calls, phone number
        provisioning, top-ups, refunds) with counts and averages.
        Useful for tracking how much your AI agents are spending on
        phone calls and phone numbers.

        Parameters
        ----------
        period : typing.Optional[str]
            Time period: 'current_month', 'last_month', 'all_time', or 'YYYY-MM'

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Any
            Successful Response

        Examples
        --------
        import asyncio

        from agentline_ai import AsyncAgentLine

        client = AsyncAgentLine(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.billing.get_expenditure()


        asyncio.run(main())
        """
        _response = await self._raw_client.get_expenditure(period=period, request_options=request_options)
        return _response.data

    async def list_call_charges(
        self,
        *,
        limit: typing.Optional[int] = None,
        offset: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> typing.Any:
        """
        List individual call charges from AI agent phone calls.

        Each entry includes the voice call duration, cost, direction
        (inbound/outbound), phone numbers involved, and timestamp.
        Shows exactly how much each AI agent call cost.

        Parameters
        ----------
        limit : typing.Optional[int]
            Maximum number of call charges to return (1-200)

        offset : typing.Optional[int]
            Number of records to skip for pagination

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Any
            Successful Response

        Examples
        --------
        import asyncio

        from agentline_ai import AsyncAgentLine

        client = AsyncAgentLine(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.billing.list_call_charges()


        asyncio.run(main())
        """
        _response = await self._raw_client.list_call_charges(
            limit=limit, offset=offset, request_options=request_options
        )
        return _response.data

    async def list_number_charges(
        self,
        *,
        limit: typing.Optional[int] = None,
        offset: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> typing.Any:
        """
        List phone number provisioning charges.

        Shows the cost of each phone number bought for your AI agents,
        including the number, country, and current status.

        Parameters
        ----------
        limit : typing.Optional[int]
            Maximum number of number charges to return (1-200)

        offset : typing.Optional[int]
            Number of records to skip for pagination

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Any
            Successful Response

        Examples
        --------
        import asyncio

        from agentline_ai import AsyncAgentLine

        client = AsyncAgentLine(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.billing.list_number_charges()


        asyncio.run(main())
        """
        _response = await self._raw_client.list_number_charges(
            limit=limit, offset=offset, request_options=request_options
        )
        return _response.data

    async def get_summary(
        self, *, months: typing.Optional[int] = None, request_options: typing.Optional[RequestOptions] = None
    ) -> typing.Any:
        """
        Month-over-month spending summary.

        Returns total debits grouped by month for trend analysis.

        Parameters
        ----------
        months : typing.Optional[int]
            Number of months to show

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Any
            Successful Response

        Examples
        --------
        import asyncio

        from agentline_ai import AsyncAgentLine

        client = AsyncAgentLine(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.billing.get_summary()


        asyncio.run(main())
        """
        _response = await self._raw_client.get_summary(months=months, request_options=request_options)
        return _response.data
