# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from .raw_client import AsyncRawMessagesClient, RawMessagesClient

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class MessagesClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawMessagesClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawMessagesClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawMessagesClient
        """
        return self._raw_client

    def list(
        self,
        *,
        agent_id: typing.Optional[str] = None,
        conversation_id: typing.Optional[str] = None,
        limit: typing.Optional[int] = None,
        offset: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> typing.Any:
        """
        List SMS messages sent and received by your AI agents.

        Returns message history with optional filters by AI agent or
        conversation. Each entry includes direction (inbound/outbound),
        phone numbers, message body, and delivery status.

        Parameters
        ----------
        agent_id : typing.Optional[str]
            Filter messages by AI agent ID

        conversation_id : typing.Optional[str]
            Filter messages by conversation thread ID

        limit : typing.Optional[int]
            Maximum number of messages to return (1-200)

        offset : typing.Optional[int]
            Number of messages to skip for pagination

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Any
            Successful Response

        Examples
        --------
        from agentline_ai import AgentLine

        client = AgentLine(
            api_key="YOUR_API_KEY",
        )
        client.messages.list()
        """
        _response = self._raw_client.list(
            agent_id=agent_id,
            conversation_id=conversation_id,
            limit=limit,
            offset=offset,
            request_options=request_options,
        )
        return _response.data

    def send(
        self,
        *,
        agent_id: str,
        to_number: str,
        body: str,
        media_url: typing.Optional[str] = OMIT,
        from_number_id: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> typing.Any:
        """
        Send an outbound SMS message from an AI agent's phone number.

        Parameters
        ----------
        agent_id : str
            ID of the AI agent sending the SMS (e.g. 'agt_abc123')

        to_number : str
            Destination phone number in E.164 format (e.g. '+12125551234')

        body : str
            SMS message text content

        media_url : typing.Optional[str]
            URL of media to attach (MMS)

        from_number_id : typing.Optional[str]
            Specific phone number ID to send from; defaults to the agent's assigned number

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Any
            Successful Response

        Examples
        --------
        from agentline_ai import AgentLine

        client = AgentLine(
            api_key="YOUR_API_KEY",
        )
        client.messages.send(
            agent_id="agent_id",
            to_number="to_number",
            body="body",
        )
        """
        _response = self._raw_client.send(
            agent_id=agent_id,
            to_number=to_number,
            body=body,
            media_url=media_url,
            from_number_id=from_number_id,
            request_options=request_options,
        )
        return _response.data

    def list_conversations(
        self, *, agent_id: typing.Optional[str] = None, request_options: typing.Optional[RequestOptions] = None
    ) -> typing.Any:
        """
        List all SMS conversations for your AI agents.

        Returns conversation threads, optionally filtered by AI agent.
        Each conversation represents an ongoing SMS exchange between
        an AI agent's phone number and an external contact.

        Parameters
        ----------
        agent_id : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Any
            Successful Response

        Examples
        --------
        from agentline_ai import AgentLine

        client = AgentLine(
            api_key="YOUR_API_KEY",
        )
        client.messages.list_conversations()
        """
        _response = self._raw_client.list_conversations(agent_id=agent_id, request_options=request_options)
        return _response.data


class AsyncMessagesClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawMessagesClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawMessagesClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawMessagesClient
        """
        return self._raw_client

    async def list(
        self,
        *,
        agent_id: typing.Optional[str] = None,
        conversation_id: typing.Optional[str] = None,
        limit: typing.Optional[int] = None,
        offset: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> typing.Any:
        """
        List SMS messages sent and received by your AI agents.

        Returns message history with optional filters by AI agent or
        conversation. Each entry includes direction (inbound/outbound),
        phone numbers, message body, and delivery status.

        Parameters
        ----------
        agent_id : typing.Optional[str]
            Filter messages by AI agent ID

        conversation_id : typing.Optional[str]
            Filter messages by conversation thread ID

        limit : typing.Optional[int]
            Maximum number of messages to return (1-200)

        offset : typing.Optional[int]
            Number of messages to skip for pagination

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Any
            Successful Response

        Examples
        --------
        import asyncio

        from agentline_ai import AsyncAgentLine

        client = AsyncAgentLine(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.messages.list()


        asyncio.run(main())
        """
        _response = await self._raw_client.list(
            agent_id=agent_id,
            conversation_id=conversation_id,
            limit=limit,
            offset=offset,
            request_options=request_options,
        )
        return _response.data

    async def send(
        self,
        *,
        agent_id: str,
        to_number: str,
        body: str,
        media_url: typing.Optional[str] = OMIT,
        from_number_id: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> typing.Any:
        """
        Send an outbound SMS message from an AI agent's phone number.

        Parameters
        ----------
        agent_id : str
            ID of the AI agent sending the SMS (e.g. 'agt_abc123')

        to_number : str
            Destination phone number in E.164 format (e.g. '+12125551234')

        body : str
            SMS message text content

        media_url : typing.Optional[str]
            URL of media to attach (MMS)

        from_number_id : typing.Optional[str]
            Specific phone number ID to send from; defaults to the agent's assigned number

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Any
            Successful Response

        Examples
        --------
        import asyncio

        from agentline_ai import AsyncAgentLine

        client = AsyncAgentLine(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.messages.send(
                agent_id="agent_id",
                to_number="to_number",
                body="body",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.send(
            agent_id=agent_id,
            to_number=to_number,
            body=body,
            media_url=media_url,
            from_number_id=from_number_id,
            request_options=request_options,
        )
        return _response.data

    async def list_conversations(
        self, *, agent_id: typing.Optional[str] = None, request_options: typing.Optional[RequestOptions] = None
    ) -> typing.Any:
        """
        List all SMS conversations for your AI agents.

        Returns conversation threads, optionally filtered by AI agent.
        Each conversation represents an ongoing SMS exchange between
        an AI agent's phone number and an external contact.

        Parameters
        ----------
        agent_id : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Any
            Successful Response

        Examples
        --------
        import asyncio

        from agentline_ai import AsyncAgentLine

        client = AsyncAgentLine(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.messages.list_conversations()


        asyncio.run(main())
        """
        _response = await self._raw_client.list_conversations(agent_id=agent_id, request_options=request_options)
        return _response.data
