# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.webhook_created import WebhookCreated
from .raw_client import AsyncRawWebhooksClient, RawWebhooksClient

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class WebhooksClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawWebhooksClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawWebhooksClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawWebhooksClient
        """
        return self._raw_client

    def list(
        self, *, agent_id: typing.Optional[str] = None, request_options: typing.Optional[RequestOptions] = None
    ) -> typing.Any:
        """
        List the account's per-agent webhook configuration(s).

        Secrets are **masked**. Pass `agent_id` to inspect a single agent's webhook.
        The full secret is only ever shown once, on the POST that creates/replaces it.

        Parameters
        ----------
        agent_id : typing.Optional[str]
            Inspect one agent's webhook (omit to list all)

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Any
            Successful Response

        Examples
        --------
        from agentline_ai import AgentLine

        client = AgentLine(
            api_key="YOUR_API_KEY",
        )
        client.webhooks.list()
        """
        _response = self._raw_client.list(agent_id=agent_id, request_options=request_options)
        return _response.data

    def set(
        self,
        *,
        url: str,
        agent_id: str,
        secret: typing.Optional[str] = OMIT,
        signature_header: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> WebhookCreated:
        """
        Create or replace an agent's webhook.

        The configured URL receives ALL of that agent's event types — call lifecycle
        (`call.received`, `call.completed`, `call.failed`), SMS (`sms.received`),
        and future events — as signed JSON POSTs. Each agent may have at most one
        webhook; POSTing again replaces it.

        - `agent_id`: the agent whose events this webhook receives (required).
        - `secret`:   HMAC signing secret. Omit to auto-generate.

        The response returns the full `secret` **once** — store it to verify the
        signature header on deliveries.

        Parameters
        ----------
        url : str
            HTTPS URL that will receive this agent's events as signed JSON POSTs. Setting this replaces any existing webhook for the agent.

        agent_id : str
            ID of the agent whose events this webhook receives. Each agent may have at most one webhook.

        secret : typing.Optional[str]
            Optional HMAC signing secret. Auto-generated if omitted. Used to verify the signature header on delivered payloads.

        signature_header : typing.Optional[str]
            Header name for the HMAC-SHA256 signature of the raw body. Defaults to 'X-Webhook-Signature' (natively verified by Hermes, OpenClaw, and other agent platforms). Set to 'X-Hub-Signature-256' for GitHub-style verification, or any custom header name your platform expects. Omit to keep the existing value when updating.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        WebhookCreated
            Successful Response

        Examples
        --------
        from agentline_ai import AgentLine

        client = AgentLine(
            api_key="YOUR_API_KEY",
        )
        client.webhooks.set(
            url="url",
            agent_id="agent_id",
        )
        """
        _response = self._raw_client.set(
            url=url,
            agent_id=agent_id,
            secret=secret,
            signature_header=signature_header,
            request_options=request_options,
        )
        return _response.data

    def delete(self, *, agent_id: str, request_options: typing.Optional[RequestOptions] = None) -> typing.Any:
        """
        Remove an agent's webhook. No events for that agent will be delivered via
        HTTP afterwards; they remain available via GET /v1/events (the mailbox).

        Parameters
        ----------
        agent_id : str
            Agent whose webhook to delete

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Any
            Successful Response

        Examples
        --------
        from agentline_ai import AgentLine

        client = AgentLine(
            api_key="YOUR_API_KEY",
        )
        client.webhooks.delete(
            agent_id="agent_id",
        )
        """
        _response = self._raw_client.delete(agent_id=agent_id, request_options=request_options)
        return _response.data

    def test(self, *, agent_id: str, request_options: typing.Optional[RequestOptions] = None) -> typing.Any:
        """
        Fire a signed `webhook.test` event to the agent's webhook.

        Uses the exact same event bus (publish_event) that real telephony events use,
        so a successful delivery confirms the entire pipeline is wired correctly.
        Returns 404 if no webhook is configured for the agent.

        Parameters
        ----------
        agent_id : str
            Agent whose webhook to test

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Any
            Successful Response

        Examples
        --------
        from agentline_ai import AgentLine

        client = AgentLine(
            api_key="YOUR_API_KEY",
        )
        client.webhooks.test(
            agent_id="agent_id",
        )
        """
        _response = self._raw_client.test(agent_id=agent_id, request_options=request_options)
        return _response.data


class AsyncWebhooksClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawWebhooksClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawWebhooksClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawWebhooksClient
        """
        return self._raw_client

    async def list(
        self, *, agent_id: typing.Optional[str] = None, request_options: typing.Optional[RequestOptions] = None
    ) -> typing.Any:
        """
        List the account's per-agent webhook configuration(s).

        Secrets are **masked**. Pass `agent_id` to inspect a single agent's webhook.
        The full secret is only ever shown once, on the POST that creates/replaces it.

        Parameters
        ----------
        agent_id : typing.Optional[str]
            Inspect one agent's webhook (omit to list all)

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Any
            Successful Response

        Examples
        --------
        import asyncio

        from agentline_ai import AsyncAgentLine

        client = AsyncAgentLine(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.webhooks.list()


        asyncio.run(main())
        """
        _response = await self._raw_client.list(agent_id=agent_id, request_options=request_options)
        return _response.data

    async def set(
        self,
        *,
        url: str,
        agent_id: str,
        secret: typing.Optional[str] = OMIT,
        signature_header: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> WebhookCreated:
        """
        Create or replace an agent's webhook.

        The configured URL receives ALL of that agent's event types — call lifecycle
        (`call.received`, `call.completed`, `call.failed`), SMS (`sms.received`),
        and future events — as signed JSON POSTs. Each agent may have at most one
        webhook; POSTing again replaces it.

        - `agent_id`: the agent whose events this webhook receives (required).
        - `secret`:   HMAC signing secret. Omit to auto-generate.

        The response returns the full `secret` **once** — store it to verify the
        signature header on deliveries.

        Parameters
        ----------
        url : str
            HTTPS URL that will receive this agent's events as signed JSON POSTs. Setting this replaces any existing webhook for the agent.

        agent_id : str
            ID of the agent whose events this webhook receives. Each agent may have at most one webhook.

        secret : typing.Optional[str]
            Optional HMAC signing secret. Auto-generated if omitted. Used to verify the signature header on delivered payloads.

        signature_header : typing.Optional[str]
            Header name for the HMAC-SHA256 signature of the raw body. Defaults to 'X-Webhook-Signature' (natively verified by Hermes, OpenClaw, and other agent platforms). Set to 'X-Hub-Signature-256' for GitHub-style verification, or any custom header name your platform expects. Omit to keep the existing value when updating.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        WebhookCreated
            Successful Response

        Examples
        --------
        import asyncio

        from agentline_ai import AsyncAgentLine

        client = AsyncAgentLine(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.webhooks.set(
                url="url",
                agent_id="agent_id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.set(
            url=url,
            agent_id=agent_id,
            secret=secret,
            signature_header=signature_header,
            request_options=request_options,
        )
        return _response.data

    async def delete(self, *, agent_id: str, request_options: typing.Optional[RequestOptions] = None) -> typing.Any:
        """
        Remove an agent's webhook. No events for that agent will be delivered via
        HTTP afterwards; they remain available via GET /v1/events (the mailbox).

        Parameters
        ----------
        agent_id : str
            Agent whose webhook to delete

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Any
            Successful Response

        Examples
        --------
        import asyncio

        from agentline_ai import AsyncAgentLine

        client = AsyncAgentLine(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.webhooks.delete(
                agent_id="agent_id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.delete(agent_id=agent_id, request_options=request_options)
        return _response.data

    async def test(self, *, agent_id: str, request_options: typing.Optional[RequestOptions] = None) -> typing.Any:
        """
        Fire a signed `webhook.test` event to the agent's webhook.

        Uses the exact same event bus (publish_event) that real telephony events use,
        so a successful delivery confirms the entire pipeline is wired correctly.
        Returns 404 if no webhook is configured for the agent.

        Parameters
        ----------
        agent_id : str
            Agent whose webhook to test

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Any
            Successful Response

        Examples
        --------
        import asyncio

        from agentline_ai import AsyncAgentLine

        client = AsyncAgentLine(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.webhooks.test(
                agent_id="agent_id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.test(agent_id=agent_id, request_options=request_options)
        return _response.data
