# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from .raw_client import AsyncRawNumbersClient, RawNumbersClient

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class NumbersClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawNumbersClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawNumbersClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawNumbersClient
        """
        return self._raw_client

    def list(self, *, request_options: typing.Optional[RequestOptions] = None) -> typing.Any:
        """
        List all phone numbers provisioned on your account.

        Returns every phone number you've bought for your AI agents,
        including which agent each number is assigned to, the number's
        status (active/released), and country.

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Any
            Successful Response

        Examples
        --------
        from agentline_ai import AgentLine

        client = AgentLine(
            token="YOUR_TOKEN",
        )
        client.numbers.list()
        """
        _response = self._raw_client.list(request_options=request_options)
        return _response.data

    def buy(
        self,
        *,
        agent_id: str,
        country: typing.Optional[str] = OMIT,
        number_type: typing.Optional[str] = OMIT,
        area_code: typing.Optional[str] = OMIT,
        pattern: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> typing.Any:
        """
        Buy a US phone number for your AI agent.

        Searches for and purchases a real US phone number from the telephony
        provider, then attaches it to the specified AI agent. Once attached,
        the agent can make outbound calls and receive inbound calls on this number.

        Each AI agent can only have ONE active phone number. Costs $2.00 per number.

        Request body:
          - agent_id: str (required) — the AI agent to assign this number to
          - country: str (must be "US")
          - number_type: "local" | "tollfree"
          - area_code: preferred 3-digit US area code (e.g. "212" for NYC, "415" for SF)

        Parameters
        ----------
        agent_id : str
            ID of the AI agent to assign this phone number to (e.g. 'agt_abc123')

        country : typing.Optional[str]
            Country code for the phone number (currently only 'US' is supported)

        number_type : typing.Optional[str]
            Type of phone number: 'local' or 'tollfree'

        area_code : typing.Optional[str]
            Preferred 3-digit US area code (e.g. '212' for NYC, '415' for SF, '310' for LA)

        pattern : typing.Optional[str]
            Legacy digit pattern match (prefer area_code instead)

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Any
            Successful Response

        Examples
        --------
        from agentline_ai import AgentLine

        client = AgentLine(
            token="YOUR_TOKEN",
        )
        client.numbers.buy(
            agent_id="agent_id",
        )
        """
        _response = self._raw_client.buy(
            agent_id=agent_id,
            country=country,
            number_type=number_type,
            area_code=area_code,
            pattern=pattern,
            request_options=request_options,
        )
        return _response.data

    def get(self, number_id: str, *, request_options: typing.Optional[RequestOptions] = None) -> typing.Any:
        """
        Get details of a specific phone number.

        Returns the phone number, its assigned AI agent, provider ID,
        country, and current status.

        Parameters
        ----------
        number_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Any
            Successful Response

        Examples
        --------
        from agentline_ai import AgentLine

        client = AgentLine(
            token="YOUR_TOKEN",
        )
        client.numbers.get(
            number_id="number_id",
        )
        """
        _response = self._raw_client.get(number_id, request_options=request_options)
        return _response.data

    def reassign(
        self, number_id: str, *, agent_id: str, request_options: typing.Optional[RequestOptions] = None
    ) -> typing.Any:
        """
        Reassign a phone number to a different AI agent.

        Moves an existing phone number from one AI agent to another.
        The target agent must not already have an active number assigned.
        The phone number remains active — only the agent ownership changes.

        Parameters
        ----------
        number_id : str

        agent_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Any
            Successful Response

        Examples
        --------
        from agentline_ai import AgentLine

        client = AgentLine(
            token="YOUR_TOKEN",
        )
        client.numbers.reassign(
            number_id="number_id",
            agent_id="agent_id",
        )
        """
        _response = self._raw_client.reassign(number_id, agent_id=agent_id, request_options=request_options)
        return _response.data


class AsyncNumbersClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawNumbersClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawNumbersClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawNumbersClient
        """
        return self._raw_client

    async def list(self, *, request_options: typing.Optional[RequestOptions] = None) -> typing.Any:
        """
        List all phone numbers provisioned on your account.

        Returns every phone number you've bought for your AI agents,
        including which agent each number is assigned to, the number's
        status (active/released), and country.

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Any
            Successful Response

        Examples
        --------
        import asyncio

        from agentline_ai import AsyncAgentLine

        client = AsyncAgentLine(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.numbers.list()


        asyncio.run(main())
        """
        _response = await self._raw_client.list(request_options=request_options)
        return _response.data

    async def buy(
        self,
        *,
        agent_id: str,
        country: typing.Optional[str] = OMIT,
        number_type: typing.Optional[str] = OMIT,
        area_code: typing.Optional[str] = OMIT,
        pattern: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> typing.Any:
        """
        Buy a US phone number for your AI agent.

        Searches for and purchases a real US phone number from the telephony
        provider, then attaches it to the specified AI agent. Once attached,
        the agent can make outbound calls and receive inbound calls on this number.

        Each AI agent can only have ONE active phone number. Costs $2.00 per number.

        Request body:
          - agent_id: str (required) — the AI agent to assign this number to
          - country: str (must be "US")
          - number_type: "local" | "tollfree"
          - area_code: preferred 3-digit US area code (e.g. "212" for NYC, "415" for SF)

        Parameters
        ----------
        agent_id : str
            ID of the AI agent to assign this phone number to (e.g. 'agt_abc123')

        country : typing.Optional[str]
            Country code for the phone number (currently only 'US' is supported)

        number_type : typing.Optional[str]
            Type of phone number: 'local' or 'tollfree'

        area_code : typing.Optional[str]
            Preferred 3-digit US area code (e.g. '212' for NYC, '415' for SF, '310' for LA)

        pattern : typing.Optional[str]
            Legacy digit pattern match (prefer area_code instead)

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Any
            Successful Response

        Examples
        --------
        import asyncio

        from agentline_ai import AsyncAgentLine

        client = AsyncAgentLine(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.numbers.buy(
                agent_id="agent_id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.buy(
            agent_id=agent_id,
            country=country,
            number_type=number_type,
            area_code=area_code,
            pattern=pattern,
            request_options=request_options,
        )
        return _response.data

    async def get(self, number_id: str, *, request_options: typing.Optional[RequestOptions] = None) -> typing.Any:
        """
        Get details of a specific phone number.

        Returns the phone number, its assigned AI agent, provider ID,
        country, and current status.

        Parameters
        ----------
        number_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Any
            Successful Response

        Examples
        --------
        import asyncio

        from agentline_ai import AsyncAgentLine

        client = AsyncAgentLine(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.numbers.get(
                number_id="number_id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get(number_id, request_options=request_options)
        return _response.data

    async def reassign(
        self, number_id: str, *, agent_id: str, request_options: typing.Optional[RequestOptions] = None
    ) -> typing.Any:
        """
        Reassign a phone number to a different AI agent.

        Moves an existing phone number from one AI agent to another.
        The target agent must not already have an active number assigned.
        The phone number remains active — only the agent ownership changes.

        Parameters
        ----------
        number_id : str

        agent_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Any
            Successful Response

        Examples
        --------
        import asyncio

        from agentline_ai import AsyncAgentLine

        client = AsyncAgentLine(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.numbers.reassign(
                number_id="number_id",
                agent_id="agent_id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.reassign(number_id, agent_id=agent_id, request_options=request_options)
        return _response.data
